// Code generated by ent, DO NOT EDIT.

package templates

const (
	// Label holds the string label denoting the templates type in the database.
	Label = "templates"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTemplate holds the string denoting the template field in the database.
	FieldTemplate = "template"
	// Table holds the table name of the templates in the database.
	Table = "templates"
)

// Columns holds all SQL columns for templates fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTemplate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
