// Code generated by ent, DO NOT EDIT.

package pollplayer

const (
	// Label holds the string label denoting the pollplayer type in the database.
	Label = "poll_player"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPollID holds the string denoting the pollid field in the database.
	FieldPollID = "poll_id"
	// FieldStartAt holds the string denoting the startat field in the database.
	FieldStartAt = "start_at"
	// FieldCloseAt holds the string denoting the closeat field in the database.
	FieldCloseAt = "close_at"
	// FieldMultipleAllowed holds the string denoting the multipleallowed field in the database.
	FieldMultipleAllowed = "multiple_allowed"
	// FieldCounters holds the string denoting the counters field in the database.
	FieldCounters = "counters"
	// EdgeRecords holds the string denoting the records edge name in mutations.
	EdgeRecords = "records"
	// EdgePoll holds the string denoting the poll edge name in mutations.
	EdgePoll = "poll"
	// Table holds the table name of the pollplayer in the database.
	Table = "poll_players"
	// RecordsTable is the table that holds the records relation/edge.
	RecordsTable = "vote_records"
	// RecordsInverseTable is the table name for the VoteRecord entity.
	// It exists in this package in order to avoid circular dependency with the "voterecord" package.
	RecordsInverseTable = "vote_records"
	// RecordsColumn is the table column denoting the records relation/edge.
	RecordsColumn = "poll_player_id"
	// PollTable is the table that holds the poll relation/edge.
	PollTable = "poll_players"
	// PollInverseTable is the table name for the Poll entity.
	// It exists in this package in order to avoid circular dependency with the "poll" package.
	PollInverseTable = "polls"
	// PollColumn is the table column denoting the poll relation/edge.
	PollColumn = "poll_id"
)

// Columns holds all SQL columns for pollplayer fields.
var Columns = []string{
	FieldID,
	FieldPollID,
	FieldStartAt,
	FieldCloseAt,
	FieldMultipleAllowed,
	FieldCounters,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
