// Code generated by ent, DO NOT EDIT.

package pollplayer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PollID applies equality check predicate on the "PollID" field. It's identical to PollIDEQ.
func PollID(v ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPollID), v))
	})
}

// StartAt applies equality check predicate on the "StartAt" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStartAt), v))
	})
}

// CloseAt applies equality check predicate on the "CloseAt" field. It's identical to CloseAtEQ.
func CloseAt(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCloseAt), v))
	})
}

// MultipleAllowed applies equality check predicate on the "MultipleAllowed" field. It's identical to MultipleAllowedEQ.
func MultipleAllowed(v bool) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMultipleAllowed), v))
	})
}

// PollIDEQ applies the EQ predicate on the "PollID" field.
func PollIDEQ(v ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPollID), v))
	})
}

// PollIDNEQ applies the NEQ predicate on the "PollID" field.
func PollIDNEQ(v ulid.ULID) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPollID), v))
	})
}

// PollIDIn applies the In predicate on the "PollID" field.
func PollIDIn(vs ...ulid.ULID) predicate.PollPlayer {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPollID), v...))
	})
}

// PollIDNotIn applies the NotIn predicate on the "PollID" field.
func PollIDNotIn(vs ...ulid.ULID) predicate.PollPlayer {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPollID), v...))
	})
}

// StartAtEQ applies the EQ predicate on the "StartAt" field.
func StartAtEQ(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStartAt), v))
	})
}

// StartAtNEQ applies the NEQ predicate on the "StartAt" field.
func StartAtNEQ(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStartAt), v))
	})
}

// StartAtIn applies the In predicate on the "StartAt" field.
func StartAtIn(vs ...time.Time) predicate.PollPlayer {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldStartAt), v...))
	})
}

// StartAtNotIn applies the NotIn predicate on the "StartAt" field.
func StartAtNotIn(vs ...time.Time) predicate.PollPlayer {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldStartAt), v...))
	})
}

// StartAtGT applies the GT predicate on the "StartAt" field.
func StartAtGT(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStartAt), v))
	})
}

// StartAtGTE applies the GTE predicate on the "StartAt" field.
func StartAtGTE(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStartAt), v))
	})
}

// StartAtLT applies the LT predicate on the "StartAt" field.
func StartAtLT(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStartAt), v))
	})
}

// StartAtLTE applies the LTE predicate on the "StartAt" field.
func StartAtLTE(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStartAt), v))
	})
}

// CloseAtEQ applies the EQ predicate on the "CloseAt" field.
func CloseAtEQ(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCloseAt), v))
	})
}

// CloseAtNEQ applies the NEQ predicate on the "CloseAt" field.
func CloseAtNEQ(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCloseAt), v))
	})
}

// CloseAtIn applies the In predicate on the "CloseAt" field.
func CloseAtIn(vs ...time.Time) predicate.PollPlayer {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCloseAt), v...))
	})
}

// CloseAtNotIn applies the NotIn predicate on the "CloseAt" field.
func CloseAtNotIn(vs ...time.Time) predicate.PollPlayer {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCloseAt), v...))
	})
}

// CloseAtGT applies the GT predicate on the "CloseAt" field.
func CloseAtGT(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCloseAt), v))
	})
}

// CloseAtGTE applies the GTE predicate on the "CloseAt" field.
func CloseAtGTE(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCloseAt), v))
	})
}

// CloseAtLT applies the LT predicate on the "CloseAt" field.
func CloseAtLT(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCloseAt), v))
	})
}

// CloseAtLTE applies the LTE predicate on the "CloseAt" field.
func CloseAtLTE(v time.Time) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCloseAt), v))
	})
}

// MultipleAllowedEQ applies the EQ predicate on the "MultipleAllowed" field.
func MultipleAllowedEQ(v bool) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMultipleAllowed), v))
	})
}

// MultipleAllowedNEQ applies the NEQ predicate on the "MultipleAllowed" field.
func MultipleAllowedNEQ(v bool) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMultipleAllowed), v))
	})
}

// HasRecords applies the HasEdge predicate on the "records" edge.
func HasRecords() predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RecordsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecordsTable, RecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordsWith applies the HasEdge predicate on the "records" edge with a given conditions (other predicates).
func HasRecordsWith(preds ...predicate.VoteRecord) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RecordsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecordsTable, RecordsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPoll applies the HasEdge predicate on the "poll" edge.
func HasPoll() predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PollTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PollTable, PollColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPollWith applies the HasEdge predicate on the "poll" edge with a given conditions (other predicates).
func HasPollWith(preds ...predicate.Poll) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PollInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PollTable, PollColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PollPlayer) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PollPlayer) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PollPlayer) predicate.PollPlayer {
	return predicate.PollPlayer(func(s *sql.Selector) {
		p(s.Not())
	})
}
