// Code generated by ent, DO NOT EDIT.

package poll

const (
	// Label holds the string label denoting the poll type in the database.
	Label = "poll"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuestion holds the string denoting the question field in the database.
	FieldQuestion = "question"
	// FieldAnswers holds the string denoting the answers field in the database.
	FieldAnswers = "answers"
	// EdgePlayers holds the string denoting the players edge name in mutations.
	EdgePlayers = "players"
	// Table holds the table name of the poll in the database.
	Table = "polls"
	// PlayersTable is the table that holds the players relation/edge.
	PlayersTable = "poll_players"
	// PlayersInverseTable is the table name for the PollPlayer entity.
	// It exists in this package in order to avoid circular dependency with the "pollplayer" package.
	PlayersInverseTable = "poll_players"
	// PlayersColumn is the table column denoting the players relation/edge.
	PlayersColumn = "poll_id"
)

// Columns holds all SQL columns for poll fields.
var Columns = []string{
	FieldID,
	FieldQuestion,
	FieldAnswers,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
