// Code generated by ent, DO NOT EDIT.

package poll

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ULID) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Question applies equality check predicate on the "Question" field. It's identical to QuestionEQ.
func Question(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldQuestion), v))
	})
}

// QuestionEQ applies the EQ predicate on the "Question" field.
func QuestionEQ(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldQuestion), v))
	})
}

// QuestionNEQ applies the NEQ predicate on the "Question" field.
func QuestionNEQ(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldQuestion), v))
	})
}

// QuestionIn applies the In predicate on the "Question" field.
func QuestionIn(vs ...string) predicate.Poll {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldQuestion), v...))
	})
}

// QuestionNotIn applies the NotIn predicate on the "Question" field.
func QuestionNotIn(vs ...string) predicate.Poll {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldQuestion), v...))
	})
}

// QuestionGT applies the GT predicate on the "Question" field.
func QuestionGT(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldQuestion), v))
	})
}

// QuestionGTE applies the GTE predicate on the "Question" field.
func QuestionGTE(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldQuestion), v))
	})
}

// QuestionLT applies the LT predicate on the "Question" field.
func QuestionLT(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldQuestion), v))
	})
}

// QuestionLTE applies the LTE predicate on the "Question" field.
func QuestionLTE(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldQuestion), v))
	})
}

// QuestionContains applies the Contains predicate on the "Question" field.
func QuestionContains(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldQuestion), v))
	})
}

// QuestionHasPrefix applies the HasPrefix predicate on the "Question" field.
func QuestionHasPrefix(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldQuestion), v))
	})
}

// QuestionHasSuffix applies the HasSuffix predicate on the "Question" field.
func QuestionHasSuffix(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldQuestion), v))
	})
}

// QuestionEqualFold applies the EqualFold predicate on the "Question" field.
func QuestionEqualFold(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldQuestion), v))
	})
}

// QuestionContainsFold applies the ContainsFold predicate on the "Question" field.
func QuestionContainsFold(v string) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldQuestion), v))
	})
}

// HasPlayers applies the HasEdge predicate on the "players" edge.
func HasPlayers() predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlayersTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlayersTable, PlayersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayersWith applies the HasEdge predicate on the "players" edge with a given conditions (other predicates).
func HasPlayersWith(preds ...predicate.PollPlayer) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlayersInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlayersTable, PlayersColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Poll) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Poll) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Poll) predicate.Poll {
	return predicate.Poll(func(s *sql.Selector) {
		p(s.Not())
	})
}
