// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Poll is the predicate function for poll builders.
type Poll func(*sql.Selector)

// PollPlayer is the predicate function for pollplayer builders.
type PollPlayer func(*sql.Selector)

// VoteRecord is the predicate function for voterecord builders.
type VoteRecord func(*sql.Selector)
