version: '3.8'

services:
  postgres:
    image: postgres:1.14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "Example"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
