openapi: 3.0.1
info:
  title: Example App
  description: |
    Exploring application, that uses specific idea of go project templating.
  version: 0.1.0
servers:
  - url: http://{hostname}/api/v1
    variables:
      hostname:
        default: localhost

paths:
  /users/{id}:
    get:
      summary: "Get user"
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: "Alexander"

