-- create "templates" table
CREATE TABLE "templates" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "template" character varying NOT NULL, PRIMARY KEY ("id"));
