-- create "polls" table
CREATE TABLE "polls" ("id" uuid NOT NULL, "question" character varying NOT NULL, "answers" jsonb NOT NULL, PRIMARY KEY ("id"));
-- create "poll_players" table
CREATE TABLE "poll_players" ("id" uuid NOT NULL, "start_at" timestamptz NOT NULL, "close_at" timestamptz NOT NULL, "multiple_allowed" boolean NOT NULL, "counters" jsonb NOT NULL, "poll_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "poll_players_polls_players" FOREIGN KEY ("poll_id") REFERENCES "polls" ("id") ON DELETE NO ACTION);
-- create "vote_records" table
CREATE TABLE "vote_records" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" character varying NOT NULL, "answers" jsonb NOT NULL, "poll_player_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "vote_records_poll_players_records" FOREIGN KEY ("poll_player_id") REFERENCES "poll_players" ("id") ON DELETE NO ACTION);
-- create index "voterecord_user_id_poll_player_id" to table: "vote_records"
CREATE UNIQUE INDEX "voterecord_user_id_poll_player_id" ON "vote_records" ("user_id", "poll_player_id");
