// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/tellmeac/go-template/internal/infrastructure/ent/runtime.go

const (
	Version = "v0.11.3"                                         // Version of ent codegen.
	Sum     = "h1:F5FBGAWiDCGder7YT+lqMnyzXl6d0xU3xMBM/SO3CMc=" // Sum of ent codegen.
)
