// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/migrate"

	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/poll"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Poll is the client for interacting with the Poll builders.
	Poll *PollClient
	// PollPlayer is the client for interacting with the PollPlayer builders.
	PollPlayer *PollPlayerClient
	// VoteRecord is the client for interacting with the VoteRecord builders.
	VoteRecord *VoteRecordClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Poll = NewPollClient(c.config)
	c.PollPlayer = NewPollPlayerClient(c.config)
	c.VoteRecord = NewVoteRecordClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Poll:       NewPollClient(cfg),
		PollPlayer: NewPollPlayerClient(cfg),
		VoteRecord: NewVoteRecordClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Poll:       NewPollClient(cfg),
		PollPlayer: NewPollPlayerClient(cfg),
		VoteRecord: NewVoteRecordClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Poll.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Poll.Use(hooks...)
	c.PollPlayer.Use(hooks...)
	c.VoteRecord.Use(hooks...)
}

// PollClient is a client for the Poll schema.
type PollClient struct {
	config
}

// NewPollClient returns a client for the Poll from the given config.
func NewPollClient(c config) *PollClient {
	return &PollClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `poll.Hooks(f(g(h())))`.
func (c *PollClient) Use(hooks ...Hook) {
	c.hooks.Poll = append(c.hooks.Poll, hooks...)
}

// Create returns a builder for creating a Poll entity.
func (c *PollClient) Create() *PollCreate {
	mutation := newPollMutation(c.config, OpCreate)
	return &PollCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Poll entities.
func (c *PollClient) CreateBulk(builders ...*PollCreate) *PollCreateBulk {
	return &PollCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Poll.
func (c *PollClient) Update() *PollUpdate {
	mutation := newPollMutation(c.config, OpUpdate)
	return &PollUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PollClient) UpdateOne(po *Poll) *PollUpdateOne {
	mutation := newPollMutation(c.config, OpUpdateOne, withPoll(po))
	return &PollUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PollClient) UpdateOneID(id ulid.ULID) *PollUpdateOne {
	mutation := newPollMutation(c.config, OpUpdateOne, withPollID(id))
	return &PollUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Poll.
func (c *PollClient) Delete() *PollDelete {
	mutation := newPollMutation(c.config, OpDelete)
	return &PollDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PollClient) DeleteOne(po *Poll) *PollDeleteOne {
	return c.DeleteOneID(po.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *PollClient) DeleteOneID(id ulid.ULID) *PollDeleteOne {
	builder := c.Delete().Where(poll.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PollDeleteOne{builder}
}

// Query returns a query builder for Poll.
func (c *PollClient) Query() *PollQuery {
	return &PollQuery{
		config: c.config,
	}
}

// Get returns a Poll entity by its id.
func (c *PollClient) Get(ctx context.Context, id ulid.ULID) (*Poll, error) {
	return c.Query().Where(poll.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PollClient) GetX(ctx context.Context, id ulid.ULID) *Poll {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPlayers queries the players edge of a Poll.
func (c *PollClient) QueryPlayers(po *Poll) *PollPlayerQuery {
	query := &PollPlayerQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := po.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(poll.Table, poll.FieldID, id),
			sqlgraph.To(pollplayer.Table, pollplayer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, poll.PlayersTable, poll.PlayersColumn),
		)
		fromV = sqlgraph.Neighbors(po.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PollClient) Hooks() []Hook {
	return c.hooks.Poll
}

// PollPlayerClient is a client for the PollPlayer schema.
type PollPlayerClient struct {
	config
}

// NewPollPlayerClient returns a client for the PollPlayer from the given config.
func NewPollPlayerClient(c config) *PollPlayerClient {
	return &PollPlayerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pollplayer.Hooks(f(g(h())))`.
func (c *PollPlayerClient) Use(hooks ...Hook) {
	c.hooks.PollPlayer = append(c.hooks.PollPlayer, hooks...)
}

// Create returns a builder for creating a PollPlayer entity.
func (c *PollPlayerClient) Create() *PollPlayerCreate {
	mutation := newPollPlayerMutation(c.config, OpCreate)
	return &PollPlayerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PollPlayer entities.
func (c *PollPlayerClient) CreateBulk(builders ...*PollPlayerCreate) *PollPlayerCreateBulk {
	return &PollPlayerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PollPlayer.
func (c *PollPlayerClient) Update() *PollPlayerUpdate {
	mutation := newPollPlayerMutation(c.config, OpUpdate)
	return &PollPlayerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PollPlayerClient) UpdateOne(pp *PollPlayer) *PollPlayerUpdateOne {
	mutation := newPollPlayerMutation(c.config, OpUpdateOne, withPollPlayer(pp))
	return &PollPlayerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PollPlayerClient) UpdateOneID(id ulid.ULID) *PollPlayerUpdateOne {
	mutation := newPollPlayerMutation(c.config, OpUpdateOne, withPollPlayerID(id))
	return &PollPlayerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PollPlayer.
func (c *PollPlayerClient) Delete() *PollPlayerDelete {
	mutation := newPollPlayerMutation(c.config, OpDelete)
	return &PollPlayerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PollPlayerClient) DeleteOne(pp *PollPlayer) *PollPlayerDeleteOne {
	return c.DeleteOneID(pp.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *PollPlayerClient) DeleteOneID(id ulid.ULID) *PollPlayerDeleteOne {
	builder := c.Delete().Where(pollplayer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PollPlayerDeleteOne{builder}
}

// Query returns a query builder for PollPlayer.
func (c *PollPlayerClient) Query() *PollPlayerQuery {
	return &PollPlayerQuery{
		config: c.config,
	}
}

// Get returns a PollPlayer entity by its id.
func (c *PollPlayerClient) Get(ctx context.Context, id ulid.ULID) (*PollPlayer, error) {
	return c.Query().Where(pollplayer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PollPlayerClient) GetX(ctx context.Context, id ulid.ULID) *PollPlayer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecords queries the records edge of a PollPlayer.
func (c *PollPlayerClient) QueryRecords(pp *PollPlayer) *VoteRecordQuery {
	query := &VoteRecordQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pp.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pollplayer.Table, pollplayer.FieldID, id),
			sqlgraph.To(voterecord.Table, voterecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pollplayer.RecordsTable, pollplayer.RecordsColumn),
		)
		fromV = sqlgraph.Neighbors(pp.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPoll queries the poll edge of a PollPlayer.
func (c *PollPlayerClient) QueryPoll(pp *PollPlayer) *PollQuery {
	query := &PollQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pp.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pollplayer.Table, pollplayer.FieldID, id),
			sqlgraph.To(poll.Table, poll.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pollplayer.PollTable, pollplayer.PollColumn),
		)
		fromV = sqlgraph.Neighbors(pp.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PollPlayerClient) Hooks() []Hook {
	return c.hooks.PollPlayer
}

// VoteRecordClient is a client for the VoteRecord schema.
type VoteRecordClient struct {
	config
}

// NewVoteRecordClient returns a client for the VoteRecord from the given config.
func NewVoteRecordClient(c config) *VoteRecordClient {
	return &VoteRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `voterecord.Hooks(f(g(h())))`.
func (c *VoteRecordClient) Use(hooks ...Hook) {
	c.hooks.VoteRecord = append(c.hooks.VoteRecord, hooks...)
}

// Create returns a builder for creating a VoteRecord entity.
func (c *VoteRecordClient) Create() *VoteRecordCreate {
	mutation := newVoteRecordMutation(c.config, OpCreate)
	return &VoteRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VoteRecord entities.
func (c *VoteRecordClient) CreateBulk(builders ...*VoteRecordCreate) *VoteRecordCreateBulk {
	return &VoteRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VoteRecord.
func (c *VoteRecordClient) Update() *VoteRecordUpdate {
	mutation := newVoteRecordMutation(c.config, OpUpdate)
	return &VoteRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VoteRecordClient) UpdateOne(vr *VoteRecord) *VoteRecordUpdateOne {
	mutation := newVoteRecordMutation(c.config, OpUpdateOne, withVoteRecord(vr))
	return &VoteRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VoteRecordClient) UpdateOneID(id int) *VoteRecordUpdateOne {
	mutation := newVoteRecordMutation(c.config, OpUpdateOne, withVoteRecordID(id))
	return &VoteRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VoteRecord.
func (c *VoteRecordClient) Delete() *VoteRecordDelete {
	mutation := newVoteRecordMutation(c.config, OpDelete)
	return &VoteRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VoteRecordClient) DeleteOne(vr *VoteRecord) *VoteRecordDeleteOne {
	return c.DeleteOneID(vr.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *VoteRecordClient) DeleteOneID(id int) *VoteRecordDeleteOne {
	builder := c.Delete().Where(voterecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VoteRecordDeleteOne{builder}
}

// Query returns a query builder for VoteRecord.
func (c *VoteRecordClient) Query() *VoteRecordQuery {
	return &VoteRecordQuery{
		config: c.config,
	}
}

// Get returns a VoteRecord entity by its id.
func (c *VoteRecordClient) Get(ctx context.Context, id int) (*VoteRecord, error) {
	return c.Query().Where(voterecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VoteRecordClient) GetX(ctx context.Context, id int) *VoteRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPlayer queries the player edge of a VoteRecord.
func (c *VoteRecordClient) QueryPlayer(vr *VoteRecord) *PollPlayerQuery {
	query := &PollPlayerQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := vr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(voterecord.Table, voterecord.FieldID, id),
			sqlgraph.To(pollplayer.Table, pollplayer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voterecord.PlayerTable, voterecord.PlayerColumn),
		)
		fromV = sqlgraph.Neighbors(vr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *VoteRecordClient) Hooks() []Hook {
	return c.hooks.VoteRecord
}
