// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/model"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/poll"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePoll       = "Poll"
	TypePollPlayer = "PollPlayer"
	TypeVoteRecord = "VoteRecord"
)

// PollMutation represents an operation that mutates the Poll nodes in the graph.
type PollMutation struct {
	config
	op             Op
	typ            string
	id             *ulid.ULID
	_Question      *string
	_Answers       *[]model.Answer
	clearedFields  map[string]struct{}
	players        map[ulid.ULID]struct{}
	removedplayers map[ulid.ULID]struct{}
	clearedplayers bool
	done           bool
	oldValue       func(context.Context) (*Poll, error)
	predicates     []predicate.Poll
}

var _ ent.Mutation = (*PollMutation)(nil)

// pollOption allows management of the mutation configuration using functional options.
type pollOption func(*PollMutation)

// newPollMutation creates new mutation for the Poll entity.
func newPollMutation(c config, op Op, opts ...pollOption) *PollMutation {
	m := &PollMutation{
		config:        c,
		op:            op,
		typ:           TypePoll,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPollID sets the ID field of the mutation.
func withPollID(id ulid.ULID) pollOption {
	return func(m *PollMutation) {
		var (
			err   error
			once  sync.Once
			value *Poll
		)
		m.oldValue = func(ctx context.Context) (*Poll, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Poll.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPoll sets the old Poll of the mutation.
func withPoll(node *Poll) pollOption {
	return func(m *PollMutation) {
		m.oldValue = func(context.Context) (*Poll, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PollMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PollMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Poll entities.
func (m *PollMutation) SetID(id ulid.ULID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PollMutation) ID() (id ulid.ULID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PollMutation) IDs(ctx context.Context) ([]ulid.ULID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []ulid.ULID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Poll.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetQuestion sets the "Question" field.
func (m *PollMutation) SetQuestion(s string) {
	m._Question = &s
}

// Question returns the value of the "Question" field in the mutation.
func (m *PollMutation) Question() (r string, exists bool) {
	v := m._Question
	if v == nil {
		return
	}
	return *v, true
}

// OldQuestion returns the old "Question" field's value of the Poll entity.
// If the Poll object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PollMutation) OldQuestion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQuestion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQuestion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQuestion: %w", err)
	}
	return oldValue.Question, nil
}

// ResetQuestion resets all changes to the "Question" field.
func (m *PollMutation) ResetQuestion() {
	m._Question = nil
}

// SetAnswers sets the "Answers" field.
func (m *PollMutation) SetAnswers(value []model.Answer) {
	m._Answers = &value
}

// Answers returns the value of the "Answers" field in the mutation.
func (m *PollMutation) Answers() (r []model.Answer, exists bool) {
	v := m._Answers
	if v == nil {
		return
	}
	return *v, true
}

// OldAnswers returns the old "Answers" field's value of the Poll entity.
// If the Poll object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PollMutation) OldAnswers(ctx context.Context) (v []model.Answer, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAnswers is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAnswers requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAnswers: %w", err)
	}
	return oldValue.Answers, nil
}

// ResetAnswers resets all changes to the "Answers" field.
func (m *PollMutation) ResetAnswers() {
	m._Answers = nil
}

// AddPlayerIDs adds the "players" edge to the PollPlayer entity by ids.
func (m *PollMutation) AddPlayerIDs(ids ...ulid.ULID) {
	if m.players == nil {
		m.players = make(map[ulid.ULID]struct{})
	}
	for i := range ids {
		m.players[ids[i]] = struct{}{}
	}
}

// ClearPlayers clears the "players" edge to the PollPlayer entity.
func (m *PollMutation) ClearPlayers() {
	m.clearedplayers = true
}

// PlayersCleared reports if the "players" edge to the PollPlayer entity was cleared.
func (m *PollMutation) PlayersCleared() bool {
	return m.clearedplayers
}

// RemovePlayerIDs removes the "players" edge to the PollPlayer entity by IDs.
func (m *PollMutation) RemovePlayerIDs(ids ...ulid.ULID) {
	if m.removedplayers == nil {
		m.removedplayers = make(map[ulid.ULID]struct{})
	}
	for i := range ids {
		delete(m.players, ids[i])
		m.removedplayers[ids[i]] = struct{}{}
	}
}

// RemovedPlayers returns the removed IDs of the "players" edge to the PollPlayer entity.
func (m *PollMutation) RemovedPlayersIDs() (ids []ulid.ULID) {
	for id := range m.removedplayers {
		ids = append(ids, id)
	}
	return
}

// PlayersIDs returns the "players" edge IDs in the mutation.
func (m *PollMutation) PlayersIDs() (ids []ulid.ULID) {
	for id := range m.players {
		ids = append(ids, id)
	}
	return
}

// ResetPlayers resets all changes to the "players" edge.
func (m *PollMutation) ResetPlayers() {
	m.players = nil
	m.clearedplayers = false
	m.removedplayers = nil
}

// Where appends a list predicates to the PollMutation builder.
func (m *PollMutation) Where(ps ...predicate.Poll) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *PollMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Poll).
func (m *PollMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PollMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m._Question != nil {
		fields = append(fields, poll.FieldQuestion)
	}
	if m._Answers != nil {
		fields = append(fields, poll.FieldAnswers)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PollMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case poll.FieldQuestion:
		return m.Question()
	case poll.FieldAnswers:
		return m.Answers()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PollMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case poll.FieldQuestion:
		return m.OldQuestion(ctx)
	case poll.FieldAnswers:
		return m.OldAnswers(ctx)
	}
	return nil, fmt.Errorf("unknown Poll field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PollMutation) SetField(name string, value ent.Value) error {
	switch name {
	case poll.FieldQuestion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQuestion(v)
		return nil
	case poll.FieldAnswers:
		v, ok := value.([]model.Answer)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAnswers(v)
		return nil
	}
	return fmt.Errorf("unknown Poll field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PollMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PollMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PollMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Poll numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PollMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PollMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PollMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Poll nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PollMutation) ResetField(name string) error {
	switch name {
	case poll.FieldQuestion:
		m.ResetQuestion()
		return nil
	case poll.FieldAnswers:
		m.ResetAnswers()
		return nil
	}
	return fmt.Errorf("unknown Poll field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PollMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.players != nil {
		edges = append(edges, poll.EdgePlayers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PollMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case poll.EdgePlayers:
		ids := make([]ent.Value, 0, len(m.players))
		for id := range m.players {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PollMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedplayers != nil {
		edges = append(edges, poll.EdgePlayers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PollMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case poll.EdgePlayers:
		ids := make([]ent.Value, 0, len(m.removedplayers))
		for id := range m.removedplayers {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PollMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedplayers {
		edges = append(edges, poll.EdgePlayers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PollMutation) EdgeCleared(name string) bool {
	switch name {
	case poll.EdgePlayers:
		return m.clearedplayers
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PollMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Poll unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PollMutation) ResetEdge(name string) error {
	switch name {
	case poll.EdgePlayers:
		m.ResetPlayers()
		return nil
	}
	return fmt.Errorf("unknown Poll edge %s", name)
}

// PollPlayerMutation represents an operation that mutates the PollPlayer nodes in the graph.
type PollPlayerMutation struct {
	config
	op               Op
	typ              string
	id               *ulid.ULID
	_StartAt         *time.Time
	_CloseAt         *time.Time
	_MultipleAllowed *bool
	_Counters        *[]model.AnswerCounter
	clearedFields    map[string]struct{}
	records          map[int]struct{}
	removedrecords   map[int]struct{}
	clearedrecords   bool
	poll             *ulid.ULID
	clearedpoll      bool
	done             bool
	oldValue         func(context.Context) (*PollPlayer, error)
	predicates       []predicate.PollPlayer
}

var _ ent.Mutation = (*PollPlayerMutation)(nil)

// pollplayerOption allows management of the mutation configuration using functional options.
type pollplayerOption func(*PollPlayerMutation)

// newPollPlayerMutation creates new mutation for the PollPlayer entity.
func newPollPlayerMutation(c config, op Op, opts ...pollplayerOption) *PollPlayerMutation {
	m := &PollPlayerMutation{
		config:        c,
		op:            op,
		typ:           TypePollPlayer,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPollPlayerID sets the ID field of the mutation.
func withPollPlayerID(id ulid.ULID) pollplayerOption {
	return func(m *PollPlayerMutation) {
		var (
			err   error
			once  sync.Once
			value *PollPlayer
		)
		m.oldValue = func(ctx context.Context) (*PollPlayer, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PollPlayer.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPollPlayer sets the old PollPlayer of the mutation.
func withPollPlayer(node *PollPlayer) pollplayerOption {
	return func(m *PollPlayerMutation) {
		m.oldValue = func(context.Context) (*PollPlayer, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PollPlayerMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PollPlayerMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PollPlayer entities.
func (m *PollPlayerMutation) SetID(id ulid.ULID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PollPlayerMutation) ID() (id ulid.ULID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PollPlayerMutation) IDs(ctx context.Context) ([]ulid.ULID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []ulid.ULID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PollPlayer.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPollID sets the "PollID" field.
func (m *PollPlayerMutation) SetPollID(u ulid.ULID) {
	m.poll = &u
}

// PollID returns the value of the "PollID" field in the mutation.
func (m *PollPlayerMutation) PollID() (r ulid.ULID, exists bool) {
	v := m.poll
	if v == nil {
		return
	}
	return *v, true
}

// OldPollID returns the old "PollID" field's value of the PollPlayer entity.
// If the PollPlayer object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PollPlayerMutation) OldPollID(ctx context.Context) (v ulid.ULID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPollID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPollID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPollID: %w", err)
	}
	return oldValue.PollID, nil
}

// ResetPollID resets all changes to the "PollID" field.
func (m *PollPlayerMutation) ResetPollID() {
	m.poll = nil
}

// SetStartAt sets the "StartAt" field.
func (m *PollPlayerMutation) SetStartAt(t time.Time) {
	m._StartAt = &t
}

// StartAt returns the value of the "StartAt" field in the mutation.
func (m *PollPlayerMutation) StartAt() (r time.Time, exists bool) {
	v := m._StartAt
	if v == nil {
		return
	}
	return *v, true
}

// OldStartAt returns the old "StartAt" field's value of the PollPlayer entity.
// If the PollPlayer object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PollPlayerMutation) OldStartAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartAt: %w", err)
	}
	return oldValue.StartAt, nil
}

// ResetStartAt resets all changes to the "StartAt" field.
func (m *PollPlayerMutation) ResetStartAt() {
	m._StartAt = nil
}

// SetCloseAt sets the "CloseAt" field.
func (m *PollPlayerMutation) SetCloseAt(t time.Time) {
	m._CloseAt = &t
}

// CloseAt returns the value of the "CloseAt" field in the mutation.
func (m *PollPlayerMutation) CloseAt() (r time.Time, exists bool) {
	v := m._CloseAt
	if v == nil {
		return
	}
	return *v, true
}

// OldCloseAt returns the old "CloseAt" field's value of the PollPlayer entity.
// If the PollPlayer object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PollPlayerMutation) OldCloseAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCloseAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCloseAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCloseAt: %w", err)
	}
	return oldValue.CloseAt, nil
}

// ResetCloseAt resets all changes to the "CloseAt" field.
func (m *PollPlayerMutation) ResetCloseAt() {
	m._CloseAt = nil
}

// SetMultipleAllowed sets the "MultipleAllowed" field.
func (m *PollPlayerMutation) SetMultipleAllowed(b bool) {
	m._MultipleAllowed = &b
}

// MultipleAllowed returns the value of the "MultipleAllowed" field in the mutation.
func (m *PollPlayerMutation) MultipleAllowed() (r bool, exists bool) {
	v := m._MultipleAllowed
	if v == nil {
		return
	}
	return *v, true
}

// OldMultipleAllowed returns the old "MultipleAllowed" field's value of the PollPlayer entity.
// If the PollPlayer object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PollPlayerMutation) OldMultipleAllowed(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMultipleAllowed is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMultipleAllowed requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMultipleAllowed: %w", err)
	}
	return oldValue.MultipleAllowed, nil
}

// ResetMultipleAllowed resets all changes to the "MultipleAllowed" field.
func (m *PollPlayerMutation) ResetMultipleAllowed() {
	m._MultipleAllowed = nil
}

// SetCounters sets the "Counters" field.
func (m *PollPlayerMutation) SetCounters(mc []model.AnswerCounter) {
	m._Counters = &mc
}

// Counters returns the value of the "Counters" field in the mutation.
func (m *PollPlayerMutation) Counters() (r []model.AnswerCounter, exists bool) {
	v := m._Counters
	if v == nil {
		return
	}
	return *v, true
}

// OldCounters returns the old "Counters" field's value of the PollPlayer entity.
// If the PollPlayer object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PollPlayerMutation) OldCounters(ctx context.Context) (v []model.AnswerCounter, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCounters is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCounters requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCounters: %w", err)
	}
	return oldValue.Counters, nil
}

// ResetCounters resets all changes to the "Counters" field.
func (m *PollPlayerMutation) ResetCounters() {
	m._Counters = nil
}

// AddRecordIDs adds the "records" edge to the VoteRecord entity by ids.
func (m *PollPlayerMutation) AddRecordIDs(ids ...int) {
	if m.records == nil {
		m.records = make(map[int]struct{})
	}
	for i := range ids {
		m.records[ids[i]] = struct{}{}
	}
}

// ClearRecords clears the "records" edge to the VoteRecord entity.
func (m *PollPlayerMutation) ClearRecords() {
	m.clearedrecords = true
}

// RecordsCleared reports if the "records" edge to the VoteRecord entity was cleared.
func (m *PollPlayerMutation) RecordsCleared() bool {
	return m.clearedrecords
}

// RemoveRecordIDs removes the "records" edge to the VoteRecord entity by IDs.
func (m *PollPlayerMutation) RemoveRecordIDs(ids ...int) {
	if m.removedrecords == nil {
		m.removedrecords = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.records, ids[i])
		m.removedrecords[ids[i]] = struct{}{}
	}
}

// RemovedRecords returns the removed IDs of the "records" edge to the VoteRecord entity.
func (m *PollPlayerMutation) RemovedRecordsIDs() (ids []int) {
	for id := range m.removedrecords {
		ids = append(ids, id)
	}
	return
}

// RecordsIDs returns the "records" edge IDs in the mutation.
func (m *PollPlayerMutation) RecordsIDs() (ids []int) {
	for id := range m.records {
		ids = append(ids, id)
	}
	return
}

// ResetRecords resets all changes to the "records" edge.
func (m *PollPlayerMutation) ResetRecords() {
	m.records = nil
	m.clearedrecords = false
	m.removedrecords = nil
}

// ClearPoll clears the "poll" edge to the Poll entity.
func (m *PollPlayerMutation) ClearPoll() {
	m.clearedpoll = true
}

// PollCleared reports if the "poll" edge to the Poll entity was cleared.
func (m *PollPlayerMutation) PollCleared() bool {
	return m.clearedpoll
}

// PollIDs returns the "poll" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// PollID instead. It exists only for internal usage by the builders.
func (m *PollPlayerMutation) PollIDs() (ids []ulid.ULID) {
	if id := m.poll; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPoll resets all changes to the "poll" edge.
func (m *PollPlayerMutation) ResetPoll() {
	m.poll = nil
	m.clearedpoll = false
}

// Where appends a list predicates to the PollPlayerMutation builder.
func (m *PollPlayerMutation) Where(ps ...predicate.PollPlayer) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *PollPlayerMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (PollPlayer).
func (m *PollPlayerMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PollPlayerMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.poll != nil {
		fields = append(fields, pollplayer.FieldPollID)
	}
	if m._StartAt != nil {
		fields = append(fields, pollplayer.FieldStartAt)
	}
	if m._CloseAt != nil {
		fields = append(fields, pollplayer.FieldCloseAt)
	}
	if m._MultipleAllowed != nil {
		fields = append(fields, pollplayer.FieldMultipleAllowed)
	}
	if m._Counters != nil {
		fields = append(fields, pollplayer.FieldCounters)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PollPlayerMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pollplayer.FieldPollID:
		return m.PollID()
	case pollplayer.FieldStartAt:
		return m.StartAt()
	case pollplayer.FieldCloseAt:
		return m.CloseAt()
	case pollplayer.FieldMultipleAllowed:
		return m.MultipleAllowed()
	case pollplayer.FieldCounters:
		return m.Counters()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PollPlayerMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pollplayer.FieldPollID:
		return m.OldPollID(ctx)
	case pollplayer.FieldStartAt:
		return m.OldStartAt(ctx)
	case pollplayer.FieldCloseAt:
		return m.OldCloseAt(ctx)
	case pollplayer.FieldMultipleAllowed:
		return m.OldMultipleAllowed(ctx)
	case pollplayer.FieldCounters:
		return m.OldCounters(ctx)
	}
	return nil, fmt.Errorf("unknown PollPlayer field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PollPlayerMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pollplayer.FieldPollID:
		v, ok := value.(ulid.ULID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPollID(v)
		return nil
	case pollplayer.FieldStartAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartAt(v)
		return nil
	case pollplayer.FieldCloseAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCloseAt(v)
		return nil
	case pollplayer.FieldMultipleAllowed:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMultipleAllowed(v)
		return nil
	case pollplayer.FieldCounters:
		v, ok := value.([]model.AnswerCounter)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCounters(v)
		return nil
	}
	return fmt.Errorf("unknown PollPlayer field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PollPlayerMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PollPlayerMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PollPlayerMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown PollPlayer numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PollPlayerMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PollPlayerMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PollPlayerMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PollPlayer nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PollPlayerMutation) ResetField(name string) error {
	switch name {
	case pollplayer.FieldPollID:
		m.ResetPollID()
		return nil
	case pollplayer.FieldStartAt:
		m.ResetStartAt()
		return nil
	case pollplayer.FieldCloseAt:
		m.ResetCloseAt()
		return nil
	case pollplayer.FieldMultipleAllowed:
		m.ResetMultipleAllowed()
		return nil
	case pollplayer.FieldCounters:
		m.ResetCounters()
		return nil
	}
	return fmt.Errorf("unknown PollPlayer field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PollPlayerMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.records != nil {
		edges = append(edges, pollplayer.EdgeRecords)
	}
	if m.poll != nil {
		edges = append(edges, pollplayer.EdgePoll)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PollPlayerMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case pollplayer.EdgeRecords:
		ids := make([]ent.Value, 0, len(m.records))
		for id := range m.records {
			ids = append(ids, id)
		}
		return ids
	case pollplayer.EdgePoll:
		if id := m.poll; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PollPlayerMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedrecords != nil {
		edges = append(edges, pollplayer.EdgeRecords)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PollPlayerMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case pollplayer.EdgeRecords:
		ids := make([]ent.Value, 0, len(m.removedrecords))
		for id := range m.removedrecords {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PollPlayerMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedrecords {
		edges = append(edges, pollplayer.EdgeRecords)
	}
	if m.clearedpoll {
		edges = append(edges, pollplayer.EdgePoll)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PollPlayerMutation) EdgeCleared(name string) bool {
	switch name {
	case pollplayer.EdgeRecords:
		return m.clearedrecords
	case pollplayer.EdgePoll:
		return m.clearedpoll
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PollPlayerMutation) ClearEdge(name string) error {
	switch name {
	case pollplayer.EdgePoll:
		m.ClearPoll()
		return nil
	}
	return fmt.Errorf("unknown PollPlayer unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PollPlayerMutation) ResetEdge(name string) error {
	switch name {
	case pollplayer.EdgeRecords:
		m.ResetRecords()
		return nil
	case pollplayer.EdgePoll:
		m.ResetPoll()
		return nil
	}
	return fmt.Errorf("unknown PollPlayer edge %s", name)
}

// VoteRecordMutation represents an operation that mutates the VoteRecord nodes in the graph.
type VoteRecordMutation struct {
	config
	op            Op
	typ           string
	id            *int
	_UserID       *string
	_Answers      *[]int
	clearedFields map[string]struct{}
	player        *ulid.ULID
	clearedplayer bool
	done          bool
	oldValue      func(context.Context) (*VoteRecord, error)
	predicates    []predicate.VoteRecord
}

var _ ent.Mutation = (*VoteRecordMutation)(nil)

// voterecordOption allows management of the mutation configuration using functional options.
type voterecordOption func(*VoteRecordMutation)

// newVoteRecordMutation creates new mutation for the VoteRecord entity.
func newVoteRecordMutation(c config, op Op, opts ...voterecordOption) *VoteRecordMutation {
	m := &VoteRecordMutation{
		config:        c,
		op:            op,
		typ:           TypeVoteRecord,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withVoteRecordID sets the ID field of the mutation.
func withVoteRecordID(id int) voterecordOption {
	return func(m *VoteRecordMutation) {
		var (
			err   error
			once  sync.Once
			value *VoteRecord
		)
		m.oldValue = func(ctx context.Context) (*VoteRecord, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().VoteRecord.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withVoteRecord sets the old VoteRecord of the mutation.
func withVoteRecord(node *VoteRecord) voterecordOption {
	return func(m *VoteRecordMutation) {
		m.oldValue = func(context.Context) (*VoteRecord, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m VoteRecordMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m VoteRecordMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *VoteRecordMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *VoteRecordMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().VoteRecord.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "UserID" field.
func (m *VoteRecordMutation) SetUserID(s string) {
	m._UserID = &s
}

// UserID returns the value of the "UserID" field in the mutation.
func (m *VoteRecordMutation) UserID() (r string, exists bool) {
	v := m._UserID
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "UserID" field's value of the VoteRecord entity.
// If the VoteRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VoteRecordMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "UserID" field.
func (m *VoteRecordMutation) ResetUserID() {
	m._UserID = nil
}

// SetPollPlayerID sets the "PollPlayerID" field.
func (m *VoteRecordMutation) SetPollPlayerID(u ulid.ULID) {
	m.player = &u
}

// PollPlayerID returns the value of the "PollPlayerID" field in the mutation.
func (m *VoteRecordMutation) PollPlayerID() (r ulid.ULID, exists bool) {
	v := m.player
	if v == nil {
		return
	}
	return *v, true
}

// OldPollPlayerID returns the old "PollPlayerID" field's value of the VoteRecord entity.
// If the VoteRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VoteRecordMutation) OldPollPlayerID(ctx context.Context) (v ulid.ULID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPollPlayerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPollPlayerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPollPlayerID: %w", err)
	}
	return oldValue.PollPlayerID, nil
}

// ResetPollPlayerID resets all changes to the "PollPlayerID" field.
func (m *VoteRecordMutation) ResetPollPlayerID() {
	m.player = nil
}

// SetAnswers sets the "Answers" field.
func (m *VoteRecordMutation) SetAnswers(i []int) {
	m._Answers = &i
}

// Answers returns the value of the "Answers" field in the mutation.
func (m *VoteRecordMutation) Answers() (r []int, exists bool) {
	v := m._Answers
	if v == nil {
		return
	}
	return *v, true
}

// OldAnswers returns the old "Answers" field's value of the VoteRecord entity.
// If the VoteRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VoteRecordMutation) OldAnswers(ctx context.Context) (v []int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAnswers is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAnswers requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAnswers: %w", err)
	}
	return oldValue.Answers, nil
}

// ResetAnswers resets all changes to the "Answers" field.
func (m *VoteRecordMutation) ResetAnswers() {
	m._Answers = nil
}

// SetPlayerID sets the "player" edge to the PollPlayer entity by id.
func (m *VoteRecordMutation) SetPlayerID(id ulid.ULID) {
	m.player = &id
}

// ClearPlayer clears the "player" edge to the PollPlayer entity.
func (m *VoteRecordMutation) ClearPlayer() {
	m.clearedplayer = true
}

// PlayerCleared reports if the "player" edge to the PollPlayer entity was cleared.
func (m *VoteRecordMutation) PlayerCleared() bool {
	return m.clearedplayer
}

// PlayerID returns the "player" edge ID in the mutation.
func (m *VoteRecordMutation) PlayerID() (id ulid.ULID, exists bool) {
	if m.player != nil {
		return *m.player, true
	}
	return
}

// PlayerIDs returns the "player" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// PlayerID instead. It exists only for internal usage by the builders.
func (m *VoteRecordMutation) PlayerIDs() (ids []ulid.ULID) {
	if id := m.player; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPlayer resets all changes to the "player" edge.
func (m *VoteRecordMutation) ResetPlayer() {
	m.player = nil
	m.clearedplayer = false
}

// Where appends a list predicates to the VoteRecordMutation builder.
func (m *VoteRecordMutation) Where(ps ...predicate.VoteRecord) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *VoteRecordMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (VoteRecord).
func (m *VoteRecordMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *VoteRecordMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m._UserID != nil {
		fields = append(fields, voterecord.FieldUserID)
	}
	if m.player != nil {
		fields = append(fields, voterecord.FieldPollPlayerID)
	}
	if m._Answers != nil {
		fields = append(fields, voterecord.FieldAnswers)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *VoteRecordMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case voterecord.FieldUserID:
		return m.UserID()
	case voterecord.FieldPollPlayerID:
		return m.PollPlayerID()
	case voterecord.FieldAnswers:
		return m.Answers()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *VoteRecordMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case voterecord.FieldUserID:
		return m.OldUserID(ctx)
	case voterecord.FieldPollPlayerID:
		return m.OldPollPlayerID(ctx)
	case voterecord.FieldAnswers:
		return m.OldAnswers(ctx)
	}
	return nil, fmt.Errorf("unknown VoteRecord field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VoteRecordMutation) SetField(name string, value ent.Value) error {
	switch name {
	case voterecord.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case voterecord.FieldPollPlayerID:
		v, ok := value.(ulid.ULID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPollPlayerID(v)
		return nil
	case voterecord.FieldAnswers:
		v, ok := value.([]int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAnswers(v)
		return nil
	}
	return fmt.Errorf("unknown VoteRecord field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *VoteRecordMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *VoteRecordMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VoteRecordMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown VoteRecord numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *VoteRecordMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *VoteRecordMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *VoteRecordMutation) ClearField(name string) error {
	return fmt.Errorf("unknown VoteRecord nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *VoteRecordMutation) ResetField(name string) error {
	switch name {
	case voterecord.FieldUserID:
		m.ResetUserID()
		return nil
	case voterecord.FieldPollPlayerID:
		m.ResetPollPlayerID()
		return nil
	case voterecord.FieldAnswers:
		m.ResetAnswers()
		return nil
	}
	return fmt.Errorf("unknown VoteRecord field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *VoteRecordMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.player != nil {
		edges = append(edges, voterecord.EdgePlayer)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *VoteRecordMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case voterecord.EdgePlayer:
		if id := m.player; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *VoteRecordMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *VoteRecordMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *VoteRecordMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedplayer {
		edges = append(edges, voterecord.EdgePlayer)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *VoteRecordMutation) EdgeCleared(name string) bool {
	switch name {
	case voterecord.EdgePlayer:
		return m.clearedplayer
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *VoteRecordMutation) ClearEdge(name string) error {
	switch name {
	case voterecord.EdgePlayer:
		m.ClearPlayer()
		return nil
	}
	return fmt.Errorf("unknown VoteRecord unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *VoteRecordMutation) ResetEdge(name string) error {
	switch name {
	case voterecord.EdgePlayer:
		m.ResetPlayer()
		return nil
	}
	return fmt.Errorf("unknown VoteRecord edge %s", name)
}
