// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/model"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/poll"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
)

// PollPlayer is the model entity for the PollPlayer schema.
type PollPlayer struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ULID `json:"id,omitempty"`
	// PollID holds the value of the "PollID" field.
	PollID ulid.ULID `json:"PollID,omitempty"`
	// StartAt holds the value of the "StartAt" field.
	StartAt time.Time `json:"StartAt,omitempty"`
	// CloseAt holds the value of the "CloseAt" field.
	CloseAt *time.Time `json:"CloseAt,omitempty"`
	// MultipleAllowed holds the value of the "MultipleAllowed" field.
	MultipleAllowed bool `json:"MultipleAllowed,omitempty"`
	// Contains list of counters for answers
	Counters []model.AnswerCounter `json:"Counters,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PollPlayerQuery when eager-loading is set.
	Edges PollPlayerEdges `json:"edges"`
}

// PollPlayerEdges holds the relations/edges for other nodes in the graph.
type PollPlayerEdges struct {
	// Records holds the value of the records edge.
	Records []*VoteRecord `json:"records,omitempty"`
	// Poll holds the value of the poll edge.
	Poll *Poll `json:"poll,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RecordsOrErr returns the Records value or an error if the edge
// was not loaded in eager-loading.
func (e PollPlayerEdges) RecordsOrErr() ([]*VoteRecord, error) {
	if e.loadedTypes[0] {
		return e.Records, nil
	}
	return nil, &NotLoadedError{edge: "records"}
}

// PollOrErr returns the Poll value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PollPlayerEdges) PollOrErr() (*Poll, error) {
	if e.loadedTypes[1] {
		if e.Poll == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: poll.Label}
		}
		return e.Poll, nil
	}
	return nil, &NotLoadedError{edge: "poll"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PollPlayer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pollplayer.FieldCounters:
			values[i] = new([]byte)
		case pollplayer.FieldMultipleAllowed:
			values[i] = new(sql.NullBool)
		case pollplayer.FieldStartAt, pollplayer.FieldCloseAt:
			values[i] = new(sql.NullTime)
		case pollplayer.FieldID, pollplayer.FieldPollID:
			values[i] = new(ulid.ULID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PollPlayer", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PollPlayer fields.
func (pp *PollPlayer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pollplayer.FieldID:
			if value, ok := values[i].(*ulid.ULID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pp.ID = *value
			}
		case pollplayer.FieldPollID:
			if value, ok := values[i].(*ulid.ULID); !ok {
				return fmt.Errorf("unexpected type %T for field PollID", values[i])
			} else if value != nil {
				pp.PollID = *value
			}
		case pollplayer.FieldStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field StartAt", values[i])
			} else if value.Valid {
				pp.StartAt = value.Time
			}
		case pollplayer.FieldCloseAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field CloseAt", values[i])
			} else if value.Valid {
				pp.CloseAt = new(time.Time)
				*pp.CloseAt = value.Time
			}
		case pollplayer.FieldMultipleAllowed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field MultipleAllowed", values[i])
			} else if value.Valid {
				pp.MultipleAllowed = value.Bool
			}
		case pollplayer.FieldCounters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field Counters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pp.Counters); err != nil {
					return fmt.Errorf("unmarshal field Counters: %w", err)
				}
			}
		}
	}
	return nil
}

// QueryRecords queries the "records" edge of the PollPlayer entity.
func (pp *PollPlayer) QueryRecords() *VoteRecordQuery {
	return (&PollPlayerClient{config: pp.config}).QueryRecords(pp)
}

// QueryPoll queries the "poll" edge of the PollPlayer entity.
func (pp *PollPlayer) QueryPoll() *PollQuery {
	return (&PollPlayerClient{config: pp.config}).QueryPoll(pp)
}

// Update returns a builder for updating this PollPlayer.
// Note that you need to call PollPlayer.Unwrap() before calling this method if this PollPlayer
// was returned from a transaction, and the transaction was committed or rolled back.
func (pp *PollPlayer) Update() *PollPlayerUpdateOne {
	return (&PollPlayerClient{config: pp.config}).UpdateOne(pp)
}

// Unwrap unwraps the PollPlayer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pp *PollPlayer) Unwrap() *PollPlayer {
	_tx, ok := pp.config.driver.(*txDriver)
	if !ok {
		panic("ent: PollPlayer is not a transactional entity")
	}
	pp.config.driver = _tx.drv
	return pp
}

// String implements the fmt.Stringer.
func (pp *PollPlayer) String() string {
	var builder strings.Builder
	builder.WriteString("PollPlayer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pp.ID))
	builder.WriteString("PollID=")
	builder.WriteString(fmt.Sprintf("%v", pp.PollID))
	builder.WriteString(", ")
	builder.WriteString("StartAt=")
	builder.WriteString(pp.StartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := pp.CloseAt; v != nil {
		builder.WriteString("CloseAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("MultipleAllowed=")
	builder.WriteString(fmt.Sprintf("%v", pp.MultipleAllowed))
	builder.WriteString(", ")
	builder.WriteString("Counters=")
	builder.WriteString(fmt.Sprintf("%v", pp.Counters))
	builder.WriteByte(')')
	return builder.String()
}

// PollPlayers is a parsable slice of PollPlayer.
type PollPlayers []*PollPlayer

func (pp PollPlayers) config(cfg config) {
	for _i := range pp {
		pp[_i].config = cfg
	}
}
