// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/poll"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// PollPlayerQuery is the builder for querying PollPlayer entities.
type PollPlayerQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.PollPlayer
	withRecords *VoteRecordQuery
	withPoll    *PollQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PollPlayerQuery builder.
func (ppq *PollPlayerQuery) Where(ps ...predicate.PollPlayer) *PollPlayerQuery {
	ppq.predicates = append(ppq.predicates, ps...)
	return ppq
}

// Limit adds a limit step to the query.
func (ppq *PollPlayerQuery) Limit(limit int) *PollPlayerQuery {
	ppq.limit = &limit
	return ppq
}

// Offset adds an offset step to the query.
func (ppq *PollPlayerQuery) Offset(offset int) *PollPlayerQuery {
	ppq.offset = &offset
	return ppq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ppq *PollPlayerQuery) Unique(unique bool) *PollPlayerQuery {
	ppq.unique = &unique
	return ppq
}

// Order adds an order step to the query.
func (ppq *PollPlayerQuery) Order(o ...OrderFunc) *PollPlayerQuery {
	ppq.order = append(ppq.order, o...)
	return ppq
}

// QueryRecords chains the current query on the "records" edge.
func (ppq *PollPlayerQuery) QueryRecords() *VoteRecordQuery {
	query := &VoteRecordQuery{config: ppq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pollplayer.Table, pollplayer.FieldID, selector),
			sqlgraph.To(voterecord.Table, voterecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pollplayer.RecordsTable, pollplayer.RecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPoll chains the current query on the "poll" edge.
func (ppq *PollPlayerQuery) QueryPoll() *PollQuery {
	query := &PollQuery{config: ppq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pollplayer.Table, pollplayer.FieldID, selector),
			sqlgraph.To(poll.Table, poll.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pollplayer.PollTable, pollplayer.PollColumn),
		)
		fromU = sqlgraph.SetNeighbors(ppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PollPlayer entity from the query.
// Returns a *NotFoundError when no PollPlayer was found.
func (ppq *PollPlayerQuery) First(ctx context.Context) (*PollPlayer, error) {
	nodes, err := ppq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pollplayer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ppq *PollPlayerQuery) FirstX(ctx context.Context) *PollPlayer {
	node, err := ppq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PollPlayer ID from the query.
// Returns a *NotFoundError when no PollPlayer ID was found.
func (ppq *PollPlayerQuery) FirstID(ctx context.Context) (id ulid.ULID, err error) {
	var ids []ulid.ULID
	if ids, err = ppq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pollplayer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ppq *PollPlayerQuery) FirstIDX(ctx context.Context) ulid.ULID {
	id, err := ppq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PollPlayer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PollPlayer entity is found.
// Returns a *NotFoundError when no PollPlayer entities are found.
func (ppq *PollPlayerQuery) Only(ctx context.Context) (*PollPlayer, error) {
	nodes, err := ppq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pollplayer.Label}
	default:
		return nil, &NotSingularError{pollplayer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ppq *PollPlayerQuery) OnlyX(ctx context.Context) *PollPlayer {
	node, err := ppq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PollPlayer ID in the query.
// Returns a *NotSingularError when more than one PollPlayer ID is found.
// Returns a *NotFoundError when no entities are found.
func (ppq *PollPlayerQuery) OnlyID(ctx context.Context) (id ulid.ULID, err error) {
	var ids []ulid.ULID
	if ids, err = ppq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pollplayer.Label}
	default:
		err = &NotSingularError{pollplayer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ppq *PollPlayerQuery) OnlyIDX(ctx context.Context) ulid.ULID {
	id, err := ppq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PollPlayers.
func (ppq *PollPlayerQuery) All(ctx context.Context) ([]*PollPlayer, error) {
	if err := ppq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ppq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ppq *PollPlayerQuery) AllX(ctx context.Context) []*PollPlayer {
	nodes, err := ppq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PollPlayer IDs.
func (ppq *PollPlayerQuery) IDs(ctx context.Context) ([]ulid.ULID, error) {
	var ids []ulid.ULID
	if err := ppq.Select(pollplayer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ppq *PollPlayerQuery) IDsX(ctx context.Context) []ulid.ULID {
	ids, err := ppq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ppq *PollPlayerQuery) Count(ctx context.Context) (int, error) {
	if err := ppq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ppq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ppq *PollPlayerQuery) CountX(ctx context.Context) int {
	count, err := ppq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ppq *PollPlayerQuery) Exist(ctx context.Context) (bool, error) {
	if err := ppq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ppq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ppq *PollPlayerQuery) ExistX(ctx context.Context) bool {
	exist, err := ppq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PollPlayerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ppq *PollPlayerQuery) Clone() *PollPlayerQuery {
	if ppq == nil {
		return nil
	}
	return &PollPlayerQuery{
		config:      ppq.config,
		limit:       ppq.limit,
		offset:      ppq.offset,
		order:       append([]OrderFunc{}, ppq.order...),
		predicates:  append([]predicate.PollPlayer{}, ppq.predicates...),
		withRecords: ppq.withRecords.Clone(),
		withPoll:    ppq.withPoll.Clone(),
		// clone intermediate query.
		sql:    ppq.sql.Clone(),
		path:   ppq.path,
		unique: ppq.unique,
	}
}

// WithRecords tells the query-builder to eager-load the nodes that are connected to
// the "records" edge. The optional arguments are used to configure the query builder of the edge.
func (ppq *PollPlayerQuery) WithRecords(opts ...func(*VoteRecordQuery)) *PollPlayerQuery {
	query := &VoteRecordQuery{config: ppq.config}
	for _, opt := range opts {
		opt(query)
	}
	ppq.withRecords = query
	return ppq
}

// WithPoll tells the query-builder to eager-load the nodes that are connected to
// the "poll" edge. The optional arguments are used to configure the query builder of the edge.
func (ppq *PollPlayerQuery) WithPoll(opts ...func(*PollQuery)) *PollPlayerQuery {
	query := &PollQuery{config: ppq.config}
	for _, opt := range opts {
		opt(query)
	}
	ppq.withPoll = query
	return ppq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PollID ulid.ULID `json:"PollID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PollPlayer.Query().
//		GroupBy(pollplayer.FieldPollID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ppq *PollPlayerQuery) GroupBy(field string, fields ...string) *PollPlayerGroupBy {
	grbuild := &PollPlayerGroupBy{config: ppq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ppq.sqlQuery(ctx), nil
	}
	grbuild.label = pollplayer.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PollID ulid.ULID `json:"PollID,omitempty"`
//	}
//
//	client.PollPlayer.Query().
//		Select(pollplayer.FieldPollID).
//		Scan(ctx, &v)
func (ppq *PollPlayerQuery) Select(fields ...string) *PollPlayerSelect {
	ppq.fields = append(ppq.fields, fields...)
	selbuild := &PollPlayerSelect{PollPlayerQuery: ppq}
	selbuild.label = pollplayer.Label
	selbuild.flds, selbuild.scan = &ppq.fields, selbuild.Scan
	return selbuild
}

func (ppq *PollPlayerQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ppq.fields {
		if !pollplayer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ppq.path != nil {
		prev, err := ppq.path(ctx)
		if err != nil {
			return err
		}
		ppq.sql = prev
	}
	return nil
}

func (ppq *PollPlayerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PollPlayer, error) {
	var (
		nodes       = []*PollPlayer{}
		_spec       = ppq.querySpec()
		loadedTypes = [2]bool{
			ppq.withRecords != nil,
			ppq.withPoll != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PollPlayer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PollPlayer{config: ppq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ppq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ppq.withRecords; query != nil {
		if err := ppq.loadRecords(ctx, query, nodes,
			func(n *PollPlayer) { n.Edges.Records = []*VoteRecord{} },
			func(n *PollPlayer, e *VoteRecord) { n.Edges.Records = append(n.Edges.Records, e) }); err != nil {
			return nil, err
		}
	}
	if query := ppq.withPoll; query != nil {
		if err := ppq.loadPoll(ctx, query, nodes, nil,
			func(n *PollPlayer, e *Poll) { n.Edges.Poll = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ppq *PollPlayerQuery) loadRecords(ctx context.Context, query *VoteRecordQuery, nodes []*PollPlayer, init func(*PollPlayer), assign func(*PollPlayer, *VoteRecord)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[ulid.ULID]*PollPlayer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.InValues(pollplayer.RecordsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PollPlayerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "PollPlayerID" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (ppq *PollPlayerQuery) loadPoll(ctx context.Context, query *PollQuery, nodes []*PollPlayer, init func(*PollPlayer), assign func(*PollPlayer, *Poll)) error {
	ids := make([]ulid.ULID, 0, len(nodes))
	nodeids := make(map[ulid.ULID][]*PollPlayer)
	for i := range nodes {
		fk := nodes[i].PollID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(poll.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "PollID" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ppq *PollPlayerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ppq.querySpec()
	_spec.Node.Columns = ppq.fields
	if len(ppq.fields) > 0 {
		_spec.Unique = ppq.unique != nil && *ppq.unique
	}
	return sqlgraph.CountNodes(ctx, ppq.driver, _spec)
}

func (ppq *PollPlayerQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := ppq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (ppq *PollPlayerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pollplayer.Table,
			Columns: pollplayer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: pollplayer.FieldID,
			},
		},
		From:   ppq.sql,
		Unique: true,
	}
	if unique := ppq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ppq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pollplayer.FieldID)
		for i := range fields {
			if fields[i] != pollplayer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ppq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ppq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ppq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ppq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ppq *PollPlayerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ppq.driver.Dialect())
	t1 := builder.Table(pollplayer.Table)
	columns := ppq.fields
	if len(columns) == 0 {
		columns = pollplayer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ppq.sql != nil {
		selector = ppq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ppq.unique != nil && *ppq.unique {
		selector.Distinct()
	}
	for _, p := range ppq.predicates {
		p(selector)
	}
	for _, p := range ppq.order {
		p(selector)
	}
	if offset := ppq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ppq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PollPlayerGroupBy is the group-by builder for PollPlayer entities.
type PollPlayerGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ppgb *PollPlayerGroupBy) Aggregate(fns ...AggregateFunc) *PollPlayerGroupBy {
	ppgb.fns = append(ppgb.fns, fns...)
	return ppgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ppgb *PollPlayerGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ppgb.path(ctx)
	if err != nil {
		return err
	}
	ppgb.sql = query
	return ppgb.sqlScan(ctx, v)
}

func (ppgb *PollPlayerGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ppgb.fields {
		if !pollplayer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ppgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ppgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ppgb *PollPlayerGroupBy) sqlQuery() *sql.Selector {
	selector := ppgb.sql.Select()
	aggregation := make([]string, 0, len(ppgb.fns))
	for _, fn := range ppgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ppgb.fields)+len(ppgb.fns))
		for _, f := range ppgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ppgb.fields...)...)
}

// PollPlayerSelect is the builder for selecting fields of PollPlayer entities.
type PollPlayerSelect struct {
	*PollPlayerQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pps *PollPlayerSelect) Scan(ctx context.Context, v any) error {
	if err := pps.prepareQuery(ctx); err != nil {
		return err
	}
	pps.sql = pps.PollPlayerQuery.sqlQuery(ctx)
	return pps.sqlScan(ctx, v)
}

func (pps *PollPlayerSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := pps.sql.Query()
	if err := pps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
