// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/model"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/poll"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// PollPlayerUpdate is the builder for updating PollPlayer entities.
type PollPlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PollPlayerMutation
}

// Where appends a list predicates to the PollPlayerUpdate builder.
func (ppu *PollPlayerUpdate) Where(ps ...predicate.PollPlayer) *PollPlayerUpdate {
	ppu.mutation.Where(ps...)
	return ppu
}

// SetPollID sets the "PollID" field.
func (ppu *PollPlayerUpdate) SetPollID(u ulid.ULID) *PollPlayerUpdate {
	ppu.mutation.SetPollID(u)
	return ppu
}

// SetStartAt sets the "StartAt" field.
func (ppu *PollPlayerUpdate) SetStartAt(t time.Time) *PollPlayerUpdate {
	ppu.mutation.SetStartAt(t)
	return ppu
}

// SetCloseAt sets the "CloseAt" field.
func (ppu *PollPlayerUpdate) SetCloseAt(t time.Time) *PollPlayerUpdate {
	ppu.mutation.SetCloseAt(t)
	return ppu
}

// SetMultipleAllowed sets the "MultipleAllowed" field.
func (ppu *PollPlayerUpdate) SetMultipleAllowed(b bool) *PollPlayerUpdate {
	ppu.mutation.SetMultipleAllowed(b)
	return ppu
}

// SetCounters sets the "Counters" field.
func (ppu *PollPlayerUpdate) SetCounters(mc []model.AnswerCounter) *PollPlayerUpdate {
	ppu.mutation.SetCounters(mc)
	return ppu
}

// AddRecordIDs adds the "records" edge to the VoteRecord entity by IDs.
func (ppu *PollPlayerUpdate) AddRecordIDs(ids ...int) *PollPlayerUpdate {
	ppu.mutation.AddRecordIDs(ids...)
	return ppu
}

// AddRecords adds the "records" edges to the VoteRecord entity.
func (ppu *PollPlayerUpdate) AddRecords(v ...*VoteRecord) *PollPlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return ppu.AddRecordIDs(ids...)
}

// SetPoll sets the "poll" edge to the Poll entity.
func (ppu *PollPlayerUpdate) SetPoll(p *Poll) *PollPlayerUpdate {
	return ppu.SetPollID(p.ID)
}

// Mutation returns the PollPlayerMutation object of the builder.
func (ppu *PollPlayerUpdate) Mutation() *PollPlayerMutation {
	return ppu.mutation
}

// ClearRecords clears all "records" edges to the VoteRecord entity.
func (ppu *PollPlayerUpdate) ClearRecords() *PollPlayerUpdate {
	ppu.mutation.ClearRecords()
	return ppu
}

// RemoveRecordIDs removes the "records" edge to VoteRecord entities by IDs.
func (ppu *PollPlayerUpdate) RemoveRecordIDs(ids ...int) *PollPlayerUpdate {
	ppu.mutation.RemoveRecordIDs(ids...)
	return ppu
}

// RemoveRecords removes "records" edges to VoteRecord entities.
func (ppu *PollPlayerUpdate) RemoveRecords(v ...*VoteRecord) *PollPlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return ppu.RemoveRecordIDs(ids...)
}

// ClearPoll clears the "poll" edge to the Poll entity.
func (ppu *PollPlayerUpdate) ClearPoll() *PollPlayerUpdate {
	ppu.mutation.ClearPoll()
	return ppu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ppu *PollPlayerUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ppu.hooks) == 0 {
		if err = ppu.check(); err != nil {
			return 0, err
		}
		affected, err = ppu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PollPlayerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ppu.check(); err != nil {
				return 0, err
			}
			ppu.mutation = mutation
			affected, err = ppu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ppu.hooks) - 1; i >= 0; i-- {
			if ppu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ppu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ppu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ppu *PollPlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := ppu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ppu *PollPlayerUpdate) Exec(ctx context.Context) error {
	_, err := ppu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppu *PollPlayerUpdate) ExecX(ctx context.Context) {
	if err := ppu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ppu *PollPlayerUpdate) check() error {
	if _, ok := ppu.mutation.PollID(); ppu.mutation.PollCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PollPlayer.poll"`)
	}
	return nil
}

func (ppu *PollPlayerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pollplayer.Table,
			Columns: pollplayer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: pollplayer.FieldID,
			},
		},
	}
	if ps := ppu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ppu.mutation.StartAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pollplayer.FieldStartAt,
		})
	}
	if value, ok := ppu.mutation.CloseAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pollplayer.FieldCloseAt,
		})
	}
	if value, ok := ppu.mutation.MultipleAllowed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: pollplayer.FieldMultipleAllowed,
		})
	}
	if value, ok := ppu.mutation.Counters(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: pollplayer.FieldCounters,
		})
	}
	if ppu.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pollplayer.RecordsTable,
			Columns: []string{pollplayer.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: voterecord.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppu.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !ppu.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pollplayer.RecordsTable,
			Columns: []string{pollplayer.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: voterecord.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppu.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pollplayer.RecordsTable,
			Columns: []string{pollplayer.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: voterecord.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ppu.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pollplayer.PollTable,
			Columns: []string{pollplayer.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: poll.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppu.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pollplayer.PollTable,
			Columns: []string{pollplayer.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: poll.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ppu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pollplayer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PollPlayerUpdateOne is the builder for updating a single PollPlayer entity.
type PollPlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PollPlayerMutation
}

// SetPollID sets the "PollID" field.
func (ppuo *PollPlayerUpdateOne) SetPollID(u ulid.ULID) *PollPlayerUpdateOne {
	ppuo.mutation.SetPollID(u)
	return ppuo
}

// SetStartAt sets the "StartAt" field.
func (ppuo *PollPlayerUpdateOne) SetStartAt(t time.Time) *PollPlayerUpdateOne {
	ppuo.mutation.SetStartAt(t)
	return ppuo
}

// SetCloseAt sets the "CloseAt" field.
func (ppuo *PollPlayerUpdateOne) SetCloseAt(t time.Time) *PollPlayerUpdateOne {
	ppuo.mutation.SetCloseAt(t)
	return ppuo
}

// SetMultipleAllowed sets the "MultipleAllowed" field.
func (ppuo *PollPlayerUpdateOne) SetMultipleAllowed(b bool) *PollPlayerUpdateOne {
	ppuo.mutation.SetMultipleAllowed(b)
	return ppuo
}

// SetCounters sets the "Counters" field.
func (ppuo *PollPlayerUpdateOne) SetCounters(mc []model.AnswerCounter) *PollPlayerUpdateOne {
	ppuo.mutation.SetCounters(mc)
	return ppuo
}

// AddRecordIDs adds the "records" edge to the VoteRecord entity by IDs.
func (ppuo *PollPlayerUpdateOne) AddRecordIDs(ids ...int) *PollPlayerUpdateOne {
	ppuo.mutation.AddRecordIDs(ids...)
	return ppuo
}

// AddRecords adds the "records" edges to the VoteRecord entity.
func (ppuo *PollPlayerUpdateOne) AddRecords(v ...*VoteRecord) *PollPlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return ppuo.AddRecordIDs(ids...)
}

// SetPoll sets the "poll" edge to the Poll entity.
func (ppuo *PollPlayerUpdateOne) SetPoll(p *Poll) *PollPlayerUpdateOne {
	return ppuo.SetPollID(p.ID)
}

// Mutation returns the PollPlayerMutation object of the builder.
func (ppuo *PollPlayerUpdateOne) Mutation() *PollPlayerMutation {
	return ppuo.mutation
}

// ClearRecords clears all "records" edges to the VoteRecord entity.
func (ppuo *PollPlayerUpdateOne) ClearRecords() *PollPlayerUpdateOne {
	ppuo.mutation.ClearRecords()
	return ppuo
}

// RemoveRecordIDs removes the "records" edge to VoteRecord entities by IDs.
func (ppuo *PollPlayerUpdateOne) RemoveRecordIDs(ids ...int) *PollPlayerUpdateOne {
	ppuo.mutation.RemoveRecordIDs(ids...)
	return ppuo
}

// RemoveRecords removes "records" edges to VoteRecord entities.
func (ppuo *PollPlayerUpdateOne) RemoveRecords(v ...*VoteRecord) *PollPlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return ppuo.RemoveRecordIDs(ids...)
}

// ClearPoll clears the "poll" edge to the Poll entity.
func (ppuo *PollPlayerUpdateOne) ClearPoll() *PollPlayerUpdateOne {
	ppuo.mutation.ClearPoll()
	return ppuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ppuo *PollPlayerUpdateOne) Select(field string, fields ...string) *PollPlayerUpdateOne {
	ppuo.fields = append([]string{field}, fields...)
	return ppuo
}

// Save executes the query and returns the updated PollPlayer entity.
func (ppuo *PollPlayerUpdateOne) Save(ctx context.Context) (*PollPlayer, error) {
	var (
		err  error
		node *PollPlayer
	)
	if len(ppuo.hooks) == 0 {
		if err = ppuo.check(); err != nil {
			return nil, err
		}
		node, err = ppuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PollPlayerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ppuo.check(); err != nil {
				return nil, err
			}
			ppuo.mutation = mutation
			node, err = ppuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ppuo.hooks) - 1; i >= 0; i-- {
			if ppuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ppuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ppuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PollPlayer)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PollPlayerMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ppuo *PollPlayerUpdateOne) SaveX(ctx context.Context) *PollPlayer {
	node, err := ppuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ppuo *PollPlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := ppuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppuo *PollPlayerUpdateOne) ExecX(ctx context.Context) {
	if err := ppuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ppuo *PollPlayerUpdateOne) check() error {
	if _, ok := ppuo.mutation.PollID(); ppuo.mutation.PollCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PollPlayer.poll"`)
	}
	return nil
}

func (ppuo *PollPlayerUpdateOne) sqlSave(ctx context.Context) (_node *PollPlayer, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pollplayer.Table,
			Columns: pollplayer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: pollplayer.FieldID,
			},
		},
	}
	id, ok := ppuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PollPlayer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ppuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pollplayer.FieldID)
		for _, f := range fields {
			if !pollplayer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pollplayer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ppuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ppuo.mutation.StartAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pollplayer.FieldStartAt,
		})
	}
	if value, ok := ppuo.mutation.CloseAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pollplayer.FieldCloseAt,
		})
	}
	if value, ok := ppuo.mutation.MultipleAllowed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: pollplayer.FieldMultipleAllowed,
		})
	}
	if value, ok := ppuo.mutation.Counters(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: pollplayer.FieldCounters,
		})
	}
	if ppuo.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pollplayer.RecordsTable,
			Columns: []string{pollplayer.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: voterecord.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppuo.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !ppuo.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pollplayer.RecordsTable,
			Columns: []string{pollplayer.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: voterecord.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppuo.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pollplayer.RecordsTable,
			Columns: []string{pollplayer.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: voterecord.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ppuo.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pollplayer.PollTable,
			Columns: []string{pollplayer.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: poll.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppuo.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pollplayer.PollTable,
			Columns: []string{pollplayer.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: poll.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PollPlayer{config: ppuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ppuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pollplayer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
