// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
)

// PollPlayerDelete is the builder for deleting a PollPlayer entity.
type PollPlayerDelete struct {
	config
	hooks    []Hook
	mutation *PollPlayerMutation
}

// Where appends a list predicates to the PollPlayerDelete builder.
func (ppd *PollPlayerDelete) Where(ps ...predicate.PollPlayer) *PollPlayerDelete {
	ppd.mutation.Where(ps...)
	return ppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppd *PollPlayerDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ppd.hooks) == 0 {
		affected, err = ppd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PollPlayerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ppd.mutation = mutation
			affected, err = ppd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ppd.hooks) - 1; i >= 0; i-- {
			if ppd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ppd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ppd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppd *PollPlayerDelete) ExecX(ctx context.Context) int {
	n, err := ppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppd *PollPlayerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: pollplayer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: pollplayer.FieldID,
			},
		},
	}
	if ps := ppd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ppd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// PollPlayerDeleteOne is the builder for deleting a single PollPlayer entity.
type PollPlayerDeleteOne struct {
	ppd *PollPlayerDelete
}

// Exec executes the deletion query.
func (ppdo *PollPlayerDeleteOne) Exec(ctx context.Context) error {
	n, err := ppdo.ppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pollplayer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppdo *PollPlayerDeleteOne) ExecX(ctx context.Context) {
	ppdo.ppd.ExecX(ctx)
}
