// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/model"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/poll"
)

// Poll is the model entity for the Poll schema.
type Poll struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ULID `json:"id,omitempty"`
	// Question holds the value of the "Question" field.
	Question string `json:"Question,omitempty"`
	// Contains list of possible answers in poll
	Answers []model.Answer `json:"Answers,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PollQuery when eager-loading is set.
	Edges PollEdges `json:"edges"`
}

// PollEdges holds the relations/edges for other nodes in the graph.
type PollEdges struct {
	// Players holds the value of the players edge.
	Players []*PollPlayer `json:"players,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlayersOrErr returns the Players value or an error if the edge
// was not loaded in eager-loading.
func (e PollEdges) PlayersOrErr() ([]*PollPlayer, error) {
	if e.loadedTypes[0] {
		return e.Players, nil
	}
	return nil, &NotLoadedError{edge: "players"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Poll) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case poll.FieldAnswers:
			values[i] = new([]byte)
		case poll.FieldQuestion:
			values[i] = new(sql.NullString)
		case poll.FieldID:
			values[i] = new(ulid.ULID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Poll", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Poll fields.
func (po *Poll) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case poll.FieldID:
			if value, ok := values[i].(*ulid.ULID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				po.ID = *value
			}
		case poll.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Question", values[i])
			} else if value.Valid {
				po.Question = value.String
			}
		case poll.FieldAnswers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field Answers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &po.Answers); err != nil {
					return fmt.Errorf("unmarshal field Answers: %w", err)
				}
			}
		}
	}
	return nil
}

// QueryPlayers queries the "players" edge of the Poll entity.
func (po *Poll) QueryPlayers() *PollPlayerQuery {
	return (&PollClient{config: po.config}).QueryPlayers(po)
}

// Update returns a builder for updating this Poll.
// Note that you need to call Poll.Unwrap() before calling this method if this Poll
// was returned from a transaction, and the transaction was committed or rolled back.
func (po *Poll) Update() *PollUpdateOne {
	return (&PollClient{config: po.config}).UpdateOne(po)
}

// Unwrap unwraps the Poll entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (po *Poll) Unwrap() *Poll {
	_tx, ok := po.config.driver.(*txDriver)
	if !ok {
		panic("ent: Poll is not a transactional entity")
	}
	po.config.driver = _tx.drv
	return po
}

// String implements the fmt.Stringer.
func (po *Poll) String() string {
	var builder strings.Builder
	builder.WriteString("Poll(")
	builder.WriteString(fmt.Sprintf("id=%v, ", po.ID))
	builder.WriteString("Question=")
	builder.WriteString(po.Question)
	builder.WriteString(", ")
	builder.WriteString("Answers=")
	builder.WriteString(fmt.Sprintf("%v", po.Answers))
	builder.WriteByte(')')
	return builder.String()
}

// Polls is a parsable slice of Poll.
type Polls []*Poll

func (po Polls) config(cfg config) {
	for _i := range po {
		po[_i].config = cfg
	}
}
