// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/model"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/poll"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// PollPlayerCreate is the builder for creating a PollPlayer entity.
type PollPlayerCreate struct {
	config
	mutation *PollPlayerMutation
	hooks    []Hook
}

// SetPollID sets the "PollID" field.
func (ppc *PollPlayerCreate) SetPollID(u ulid.ULID) *PollPlayerCreate {
	ppc.mutation.SetPollID(u)
	return ppc
}

// SetStartAt sets the "StartAt" field.
func (ppc *PollPlayerCreate) SetStartAt(t time.Time) *PollPlayerCreate {
	ppc.mutation.SetStartAt(t)
	return ppc
}

// SetCloseAt sets the "CloseAt" field.
func (ppc *PollPlayerCreate) SetCloseAt(t time.Time) *PollPlayerCreate {
	ppc.mutation.SetCloseAt(t)
	return ppc
}

// SetMultipleAllowed sets the "MultipleAllowed" field.
func (ppc *PollPlayerCreate) SetMultipleAllowed(b bool) *PollPlayerCreate {
	ppc.mutation.SetMultipleAllowed(b)
	return ppc
}

// SetCounters sets the "Counters" field.
func (ppc *PollPlayerCreate) SetCounters(mc []model.AnswerCounter) *PollPlayerCreate {
	ppc.mutation.SetCounters(mc)
	return ppc
}

// SetID sets the "id" field.
func (ppc *PollPlayerCreate) SetID(u ulid.ULID) *PollPlayerCreate {
	ppc.mutation.SetID(u)
	return ppc
}

// AddRecordIDs adds the "records" edge to the VoteRecord entity by IDs.
func (ppc *PollPlayerCreate) AddRecordIDs(ids ...int) *PollPlayerCreate {
	ppc.mutation.AddRecordIDs(ids...)
	return ppc
}

// AddRecords adds the "records" edges to the VoteRecord entity.
func (ppc *PollPlayerCreate) AddRecords(v ...*VoteRecord) *PollPlayerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return ppc.AddRecordIDs(ids...)
}

// SetPoll sets the "poll" edge to the Poll entity.
func (ppc *PollPlayerCreate) SetPoll(p *Poll) *PollPlayerCreate {
	return ppc.SetPollID(p.ID)
}

// Mutation returns the PollPlayerMutation object of the builder.
func (ppc *PollPlayerCreate) Mutation() *PollPlayerMutation {
	return ppc.mutation
}

// Save creates the PollPlayer in the database.
func (ppc *PollPlayerCreate) Save(ctx context.Context) (*PollPlayer, error) {
	var (
		err  error
		node *PollPlayer
	)
	if len(ppc.hooks) == 0 {
		if err = ppc.check(); err != nil {
			return nil, err
		}
		node, err = ppc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PollPlayerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ppc.check(); err != nil {
				return nil, err
			}
			ppc.mutation = mutation
			if node, err = ppc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ppc.hooks) - 1; i >= 0; i-- {
			if ppc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ppc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ppc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PollPlayer)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PollPlayerMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ppc *PollPlayerCreate) SaveX(ctx context.Context) *PollPlayer {
	v, err := ppc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppc *PollPlayerCreate) Exec(ctx context.Context) error {
	_, err := ppc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppc *PollPlayerCreate) ExecX(ctx context.Context) {
	if err := ppc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ppc *PollPlayerCreate) check() error {
	if _, ok := ppc.mutation.PollID(); !ok {
		return &ValidationError{Name: "PollID", err: errors.New(`ent: missing required field "PollPlayer.PollID"`)}
	}
	if _, ok := ppc.mutation.StartAt(); !ok {
		return &ValidationError{Name: "StartAt", err: errors.New(`ent: missing required field "PollPlayer.StartAt"`)}
	}
	if _, ok := ppc.mutation.CloseAt(); !ok {
		return &ValidationError{Name: "CloseAt", err: errors.New(`ent: missing required field "PollPlayer.CloseAt"`)}
	}
	if _, ok := ppc.mutation.MultipleAllowed(); !ok {
		return &ValidationError{Name: "MultipleAllowed", err: errors.New(`ent: missing required field "PollPlayer.MultipleAllowed"`)}
	}
	if _, ok := ppc.mutation.Counters(); !ok {
		return &ValidationError{Name: "Counters", err: errors.New(`ent: missing required field "PollPlayer.Counters"`)}
	}
	if _, ok := ppc.mutation.PollID(); !ok {
		return &ValidationError{Name: "poll", err: errors.New(`ent: missing required edge "PollPlayer.poll"`)}
	}
	return nil
}

func (ppc *PollPlayerCreate) sqlSave(ctx context.Context) (*PollPlayer, error) {
	_node, _spec := ppc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ppc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ULID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (ppc *PollPlayerCreate) createSpec() (*PollPlayer, *sqlgraph.CreateSpec) {
	var (
		_node = &PollPlayer{config: ppc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pollplayer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: pollplayer.FieldID,
			},
		}
	)
	if id, ok := ppc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ppc.mutation.StartAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pollplayer.FieldStartAt,
		})
		_node.StartAt = value
	}
	if value, ok := ppc.mutation.CloseAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pollplayer.FieldCloseAt,
		})
		_node.CloseAt = &value
	}
	if value, ok := ppc.mutation.MultipleAllowed(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: pollplayer.FieldMultipleAllowed,
		})
		_node.MultipleAllowed = value
	}
	if value, ok := ppc.mutation.Counters(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: pollplayer.FieldCounters,
		})
		_node.Counters = value
	}
	if nodes := ppc.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pollplayer.RecordsTable,
			Columns: []string{pollplayer.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: voterecord.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ppc.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pollplayer.PollTable,
			Columns: []string{pollplayer.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: poll.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PollID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PollPlayerCreateBulk is the builder for creating many PollPlayer entities in bulk.
type PollPlayerCreateBulk struct {
	config
	builders []*PollPlayerCreate
}

// Save creates the PollPlayer entities in the database.
func (ppcb *PollPlayerCreateBulk) Save(ctx context.Context) ([]*PollPlayer, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ppcb.builders))
	nodes := make([]*PollPlayer, len(ppcb.builders))
	mutators := make([]Mutator, len(ppcb.builders))
	for i := range ppcb.builders {
		func(i int, root context.Context) {
			builder := ppcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PollPlayerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ppcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ppcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ppcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ppcb *PollPlayerCreateBulk) SaveX(ctx context.Context) []*PollPlayer {
	v, err := ppcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppcb *PollPlayerCreateBulk) Exec(ctx context.Context) error {
	_, err := ppcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppcb *PollPlayerCreateBulk) ExecX(ctx context.Context) {
	if err := ppcb.Exec(ctx); err != nil {
		panic(err)
	}
}
