// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// VoteRecord is the model entity for the VoteRecord schema.
type VoteRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "UserID" field.
	UserID string `json:"UserID,omitempty"`
	// PollPlayerID holds the value of the "PollPlayerID" field.
	PollPlayerID ulid.ULID `json:"PollPlayerID,omitempty"`
	// Contains number of requested answers in poll
	Answers []int `json:"Answers,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VoteRecordQuery when eager-loading is set.
	Edges VoteRecordEdges `json:"edges"`
}

// VoteRecordEdges holds the relations/edges for other nodes in the graph.
type VoteRecordEdges struct {
	// Player holds the value of the player edge.
	Player *PollPlayer `json:"player,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlayerOrErr returns the Player value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteRecordEdges) PlayerOrErr() (*PollPlayer, error) {
	if e.loadedTypes[0] {
		if e.Player == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: pollplayer.Label}
		}
		return e.Player, nil
	}
	return nil, &NotLoadedError{edge: "player"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VoteRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case voterecord.FieldAnswers:
			values[i] = new([]byte)
		case voterecord.FieldID:
			values[i] = new(sql.NullInt64)
		case voterecord.FieldUserID:
			values[i] = new(sql.NullString)
		case voterecord.FieldPollPlayerID:
			values[i] = new(ulid.ULID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type VoteRecord", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VoteRecord fields.
func (vr *VoteRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case voterecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			vr.ID = int(value.Int64)
		case voterecord.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field UserID", values[i])
			} else if value.Valid {
				vr.UserID = value.String
			}
		case voterecord.FieldPollPlayerID:
			if value, ok := values[i].(*ulid.ULID); !ok {
				return fmt.Errorf("unexpected type %T for field PollPlayerID", values[i])
			} else if value != nil {
				vr.PollPlayerID = *value
			}
		case voterecord.FieldAnswers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field Answers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &vr.Answers); err != nil {
					return fmt.Errorf("unmarshal field Answers: %w", err)
				}
			}
		}
	}
	return nil
}

// QueryPlayer queries the "player" edge of the VoteRecord entity.
func (vr *VoteRecord) QueryPlayer() *PollPlayerQuery {
	return (&VoteRecordClient{config: vr.config}).QueryPlayer(vr)
}

// Update returns a builder for updating this VoteRecord.
// Note that you need to call VoteRecord.Unwrap() before calling this method if this VoteRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (vr *VoteRecord) Update() *VoteRecordUpdateOne {
	return (&VoteRecordClient{config: vr.config}).UpdateOne(vr)
}

// Unwrap unwraps the VoteRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (vr *VoteRecord) Unwrap() *VoteRecord {
	_tx, ok := vr.config.driver.(*txDriver)
	if !ok {
		panic("ent: VoteRecord is not a transactional entity")
	}
	vr.config.driver = _tx.drv
	return vr
}

// String implements the fmt.Stringer.
func (vr *VoteRecord) String() string {
	var builder strings.Builder
	builder.WriteString("VoteRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", vr.ID))
	builder.WriteString("UserID=")
	builder.WriteString(vr.UserID)
	builder.WriteString(", ")
	builder.WriteString("PollPlayerID=")
	builder.WriteString(fmt.Sprintf("%v", vr.PollPlayerID))
	builder.WriteString(", ")
	builder.WriteString("Answers=")
	builder.WriteString(fmt.Sprintf("%v", vr.Answers))
	builder.WriteByte(')')
	return builder.String()
}

// VoteRecords is a parsable slice of VoteRecord.
type VoteRecords []*VoteRecord

func (vr VoteRecords) config(cfg config) {
	for _i := range vr {
		vr[_i].config = cfg
	}
}
