// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// VoteRecordQuery is the builder for querying VoteRecord entities.
type VoteRecordQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.VoteRecord
	withPlayer *PollPlayerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoteRecordQuery builder.
func (vrq *VoteRecordQuery) Where(ps ...predicate.VoteRecord) *VoteRecordQuery {
	vrq.predicates = append(vrq.predicates, ps...)
	return vrq
}

// Limit adds a limit step to the query.
func (vrq *VoteRecordQuery) Limit(limit int) *VoteRecordQuery {
	vrq.limit = &limit
	return vrq
}

// Offset adds an offset step to the query.
func (vrq *VoteRecordQuery) Offset(offset int) *VoteRecordQuery {
	vrq.offset = &offset
	return vrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vrq *VoteRecordQuery) Unique(unique bool) *VoteRecordQuery {
	vrq.unique = &unique
	return vrq
}

// Order adds an order step to the query.
func (vrq *VoteRecordQuery) Order(o ...OrderFunc) *VoteRecordQuery {
	vrq.order = append(vrq.order, o...)
	return vrq
}

// QueryPlayer chains the current query on the "player" edge.
func (vrq *VoteRecordQuery) QueryPlayer() *PollPlayerQuery {
	query := &PollPlayerQuery{config: vrq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(voterecord.Table, voterecord.FieldID, selector),
			sqlgraph.To(pollplayer.Table, pollplayer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voterecord.PlayerTable, voterecord.PlayerColumn),
		)
		fromU = sqlgraph.SetNeighbors(vrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VoteRecord entity from the query.
// Returns a *NotFoundError when no VoteRecord was found.
func (vrq *VoteRecordQuery) First(ctx context.Context) (*VoteRecord, error) {
	nodes, err := vrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{voterecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vrq *VoteRecordQuery) FirstX(ctx context.Context) *VoteRecord {
	node, err := vrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VoteRecord ID from the query.
// Returns a *NotFoundError when no VoteRecord ID was found.
func (vrq *VoteRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{voterecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vrq *VoteRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := vrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VoteRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VoteRecord entity is found.
// Returns a *NotFoundError when no VoteRecord entities are found.
func (vrq *VoteRecordQuery) Only(ctx context.Context) (*VoteRecord, error) {
	nodes, err := vrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{voterecord.Label}
	default:
		return nil, &NotSingularError{voterecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vrq *VoteRecordQuery) OnlyX(ctx context.Context) *VoteRecord {
	node, err := vrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VoteRecord ID in the query.
// Returns a *NotSingularError when more than one VoteRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (vrq *VoteRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{voterecord.Label}
	default:
		err = &NotSingularError{voterecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vrq *VoteRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := vrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VoteRecords.
func (vrq *VoteRecordQuery) All(ctx context.Context) ([]*VoteRecord, error) {
	if err := vrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vrq *VoteRecordQuery) AllX(ctx context.Context) []*VoteRecord {
	nodes, err := vrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VoteRecord IDs.
func (vrq *VoteRecordQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := vrq.Select(voterecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vrq *VoteRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := vrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vrq *VoteRecordQuery) Count(ctx context.Context) (int, error) {
	if err := vrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vrq *VoteRecordQuery) CountX(ctx context.Context) int {
	count, err := vrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vrq *VoteRecordQuery) Exist(ctx context.Context) (bool, error) {
	if err := vrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vrq *VoteRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := vrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoteRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vrq *VoteRecordQuery) Clone() *VoteRecordQuery {
	if vrq == nil {
		return nil
	}
	return &VoteRecordQuery{
		config:     vrq.config,
		limit:      vrq.limit,
		offset:     vrq.offset,
		order:      append([]OrderFunc{}, vrq.order...),
		predicates: append([]predicate.VoteRecord{}, vrq.predicates...),
		withPlayer: vrq.withPlayer.Clone(),
		// clone intermediate query.
		sql:    vrq.sql.Clone(),
		path:   vrq.path,
		unique: vrq.unique,
	}
}

// WithPlayer tells the query-builder to eager-load the nodes that are connected to
// the "player" edge. The optional arguments are used to configure the query builder of the edge.
func (vrq *VoteRecordQuery) WithPlayer(opts ...func(*PollPlayerQuery)) *VoteRecordQuery {
	query := &PollPlayerQuery{config: vrq.config}
	for _, opt := range opts {
		opt(query)
	}
	vrq.withPlayer = query
	return vrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"UserID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VoteRecord.Query().
//		GroupBy(voterecord.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vrq *VoteRecordQuery) GroupBy(field string, fields ...string) *VoteRecordGroupBy {
	grbuild := &VoteRecordGroupBy{config: vrq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vrq.sqlQuery(ctx), nil
	}
	grbuild.label = voterecord.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"UserID,omitempty"`
//	}
//
//	client.VoteRecord.Query().
//		Select(voterecord.FieldUserID).
//		Scan(ctx, &v)
func (vrq *VoteRecordQuery) Select(fields ...string) *VoteRecordSelect {
	vrq.fields = append(vrq.fields, fields...)
	selbuild := &VoteRecordSelect{VoteRecordQuery: vrq}
	selbuild.label = voterecord.Label
	selbuild.flds, selbuild.scan = &vrq.fields, selbuild.Scan
	return selbuild
}

func (vrq *VoteRecordQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vrq.fields {
		if !voterecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vrq.path != nil {
		prev, err := vrq.path(ctx)
		if err != nil {
			return err
		}
		vrq.sql = prev
	}
	return nil
}

func (vrq *VoteRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VoteRecord, error) {
	var (
		nodes       = []*VoteRecord{}
		_spec       = vrq.querySpec()
		loadedTypes = [1]bool{
			vrq.withPlayer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VoteRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VoteRecord{config: vrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vrq.withPlayer; query != nil {
		if err := vrq.loadPlayer(ctx, query, nodes, nil,
			func(n *VoteRecord, e *PollPlayer) { n.Edges.Player = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vrq *VoteRecordQuery) loadPlayer(ctx context.Context, query *PollPlayerQuery, nodes []*VoteRecord, init func(*VoteRecord), assign func(*VoteRecord, *PollPlayer)) error {
	ids := make([]ulid.ULID, 0, len(nodes))
	nodeids := make(map[ulid.ULID][]*VoteRecord)
	for i := range nodes {
		fk := nodes[i].PollPlayerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(pollplayer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "PollPlayerID" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vrq *VoteRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vrq.querySpec()
	_spec.Node.Columns = vrq.fields
	if len(vrq.fields) > 0 {
		_spec.Unique = vrq.unique != nil && *vrq.unique
	}
	return sqlgraph.CountNodes(ctx, vrq.driver, _spec)
}

func (vrq *VoteRecordQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := vrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (vrq *VoteRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   voterecord.Table,
			Columns: voterecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: voterecord.FieldID,
			},
		},
		From:   vrq.sql,
		Unique: true,
	}
	if unique := vrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voterecord.FieldID)
		for i := range fields {
			if fields[i] != voterecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vrq *VoteRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vrq.driver.Dialect())
	t1 := builder.Table(voterecord.Table)
	columns := vrq.fields
	if len(columns) == 0 {
		columns = voterecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vrq.sql != nil {
		selector = vrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vrq.unique != nil && *vrq.unique {
		selector.Distinct()
	}
	for _, p := range vrq.predicates {
		p(selector)
	}
	for _, p := range vrq.order {
		p(selector)
	}
	if offset := vrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VoteRecordGroupBy is the group-by builder for VoteRecord entities.
type VoteRecordGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vrgb *VoteRecordGroupBy) Aggregate(fns ...AggregateFunc) *VoteRecordGroupBy {
	vrgb.fns = append(vrgb.fns, fns...)
	return vrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (vrgb *VoteRecordGroupBy) Scan(ctx context.Context, v any) error {
	query, err := vrgb.path(ctx)
	if err != nil {
		return err
	}
	vrgb.sql = query
	return vrgb.sqlScan(ctx, v)
}

func (vrgb *VoteRecordGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range vrgb.fields {
		if !voterecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vrgb *VoteRecordGroupBy) sqlQuery() *sql.Selector {
	selector := vrgb.sql.Select()
	aggregation := make([]string, 0, len(vrgb.fns))
	for _, fn := range vrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(vrgb.fields)+len(vrgb.fns))
		for _, f := range vrgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(vrgb.fields...)...)
}

// VoteRecordSelect is the builder for selecting fields of VoteRecord entities.
type VoteRecordSelect struct {
	*VoteRecordQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (vrs *VoteRecordSelect) Scan(ctx context.Context, v any) error {
	if err := vrs.prepareQuery(ctx); err != nil {
		return err
	}
	vrs.sql = vrs.VoteRecordQuery.sqlQuery(ctx)
	return vrs.sqlScan(ctx, v)
}

func (vrs *VoteRecordSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := vrs.sql.Query()
	if err := vrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
