// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// VoteRecordDelete is the builder for deleting a VoteRecord entity.
type VoteRecordDelete struct {
	config
	hooks    []Hook
	mutation *VoteRecordMutation
}

// Where appends a list predicates to the VoteRecordDelete builder.
func (vrd *VoteRecordDelete) Where(ps ...predicate.VoteRecord) *VoteRecordDelete {
	vrd.mutation.Where(ps...)
	return vrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vrd *VoteRecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vrd.hooks) == 0 {
		affected, err = vrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VoteRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vrd.mutation = mutation
			affected, err = vrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vrd.hooks) - 1; i >= 0; i-- {
			if vrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (vrd *VoteRecordDelete) ExecX(ctx context.Context) int {
	n, err := vrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vrd *VoteRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: voterecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: voterecord.FieldID,
			},
		},
	}
	if ps := vrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// VoteRecordDeleteOne is the builder for deleting a single VoteRecord entity.
type VoteRecordDeleteOne struct {
	vrd *VoteRecordDelete
}

// Exec executes the deletion query.
func (vrdo *VoteRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := vrdo.vrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{voterecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vrdo *VoteRecordDeleteOne) ExecX(ctx context.Context) {
	vrdo.vrd.ExecX(ctx)
}
