// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// VoteRecordUpdate is the builder for updating VoteRecord entities.
type VoteRecordUpdate struct {
	config
	hooks    []Hook
	mutation *VoteRecordMutation
}

// Where appends a list predicates to the VoteRecordUpdate builder.
func (vru *VoteRecordUpdate) Where(ps ...predicate.VoteRecord) *VoteRecordUpdate {
	vru.mutation.Where(ps...)
	return vru
}

// SetUserID sets the "UserID" field.
func (vru *VoteRecordUpdate) SetUserID(s string) *VoteRecordUpdate {
	vru.mutation.SetUserID(s)
	return vru
}

// SetPollPlayerID sets the "PollPlayerID" field.
func (vru *VoteRecordUpdate) SetPollPlayerID(u ulid.ULID) *VoteRecordUpdate {
	vru.mutation.SetPollPlayerID(u)
	return vru
}

// SetAnswers sets the "Answers" field.
func (vru *VoteRecordUpdate) SetAnswers(i []int) *VoteRecordUpdate {
	vru.mutation.SetAnswers(i)
	return vru
}

// SetPlayerID sets the "player" edge to the PollPlayer entity by ID.
func (vru *VoteRecordUpdate) SetPlayerID(id ulid.ULID) *VoteRecordUpdate {
	vru.mutation.SetPlayerID(id)
	return vru
}

// SetPlayer sets the "player" edge to the PollPlayer entity.
func (vru *VoteRecordUpdate) SetPlayer(p *PollPlayer) *VoteRecordUpdate {
	return vru.SetPlayerID(p.ID)
}

// Mutation returns the VoteRecordMutation object of the builder.
func (vru *VoteRecordUpdate) Mutation() *VoteRecordMutation {
	return vru.mutation
}

// ClearPlayer clears the "player" edge to the PollPlayer entity.
func (vru *VoteRecordUpdate) ClearPlayer() *VoteRecordUpdate {
	vru.mutation.ClearPlayer()
	return vru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vru *VoteRecordUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vru.hooks) == 0 {
		if err = vru.check(); err != nil {
			return 0, err
		}
		affected, err = vru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VoteRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vru.check(); err != nil {
				return 0, err
			}
			vru.mutation = mutation
			affected, err = vru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vru.hooks) - 1; i >= 0; i-- {
			if vru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (vru *VoteRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := vru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vru *VoteRecordUpdate) Exec(ctx context.Context) error {
	_, err := vru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vru *VoteRecordUpdate) ExecX(ctx context.Context) {
	if err := vru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vru *VoteRecordUpdate) check() error {
	if _, ok := vru.mutation.PlayerID(); vru.mutation.PlayerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "VoteRecord.player"`)
	}
	return nil
}

func (vru *VoteRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   voterecord.Table,
			Columns: voterecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: voterecord.FieldID,
			},
		},
	}
	if ps := vru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vru.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voterecord.FieldUserID,
		})
	}
	if value, ok := vru.mutation.Answers(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: voterecord.FieldAnswers,
		})
	}
	if vru.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voterecord.PlayerTable,
			Columns: []string{voterecord.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pollplayer.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vru.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voterecord.PlayerTable,
			Columns: []string{voterecord.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pollplayer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voterecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// VoteRecordUpdateOne is the builder for updating a single VoteRecord entity.
type VoteRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoteRecordMutation
}

// SetUserID sets the "UserID" field.
func (vruo *VoteRecordUpdateOne) SetUserID(s string) *VoteRecordUpdateOne {
	vruo.mutation.SetUserID(s)
	return vruo
}

// SetPollPlayerID sets the "PollPlayerID" field.
func (vruo *VoteRecordUpdateOne) SetPollPlayerID(u ulid.ULID) *VoteRecordUpdateOne {
	vruo.mutation.SetPollPlayerID(u)
	return vruo
}

// SetAnswers sets the "Answers" field.
func (vruo *VoteRecordUpdateOne) SetAnswers(i []int) *VoteRecordUpdateOne {
	vruo.mutation.SetAnswers(i)
	return vruo
}

// SetPlayerID sets the "player" edge to the PollPlayer entity by ID.
func (vruo *VoteRecordUpdateOne) SetPlayerID(id ulid.ULID) *VoteRecordUpdateOne {
	vruo.mutation.SetPlayerID(id)
	return vruo
}

// SetPlayer sets the "player" edge to the PollPlayer entity.
func (vruo *VoteRecordUpdateOne) SetPlayer(p *PollPlayer) *VoteRecordUpdateOne {
	return vruo.SetPlayerID(p.ID)
}

// Mutation returns the VoteRecordMutation object of the builder.
func (vruo *VoteRecordUpdateOne) Mutation() *VoteRecordMutation {
	return vruo.mutation
}

// ClearPlayer clears the "player" edge to the PollPlayer entity.
func (vruo *VoteRecordUpdateOne) ClearPlayer() *VoteRecordUpdateOne {
	vruo.mutation.ClearPlayer()
	return vruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vruo *VoteRecordUpdateOne) Select(field string, fields ...string) *VoteRecordUpdateOne {
	vruo.fields = append([]string{field}, fields...)
	return vruo
}

// Save executes the query and returns the updated VoteRecord entity.
func (vruo *VoteRecordUpdateOne) Save(ctx context.Context) (*VoteRecord, error) {
	var (
		err  error
		node *VoteRecord
	)
	if len(vruo.hooks) == 0 {
		if err = vruo.check(); err != nil {
			return nil, err
		}
		node, err = vruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VoteRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vruo.check(); err != nil {
				return nil, err
			}
			vruo.mutation = mutation
			node, err = vruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(vruo.hooks) - 1; i >= 0; i-- {
			if vruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, vruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*VoteRecord)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from VoteRecordMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (vruo *VoteRecordUpdateOne) SaveX(ctx context.Context) *VoteRecord {
	node, err := vruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vruo *VoteRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := vruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vruo *VoteRecordUpdateOne) ExecX(ctx context.Context) {
	if err := vruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vruo *VoteRecordUpdateOne) check() error {
	if _, ok := vruo.mutation.PlayerID(); vruo.mutation.PlayerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "VoteRecord.player"`)
	}
	return nil
}

func (vruo *VoteRecordUpdateOne) sqlSave(ctx context.Context) (_node *VoteRecord, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   voterecord.Table,
			Columns: voterecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: voterecord.FieldID,
			},
		},
	}
	id, ok := vruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VoteRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voterecord.FieldID)
		for _, f := range fields {
			if !voterecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != voterecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vruo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voterecord.FieldUserID,
		})
	}
	if value, ok := vruo.mutation.Answers(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: voterecord.FieldAnswers,
		})
	}
	if vruo.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voterecord.PlayerTable,
			Columns: []string{voterecord.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pollplayer.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vruo.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voterecord.PlayerTable,
			Columns: []string{voterecord.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pollplayer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VoteRecord{config: vruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voterecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
