// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/pollplayer"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/voterecord"
)

// VoteRecordCreate is the builder for creating a VoteRecord entity.
type VoteRecordCreate struct {
	config
	mutation *VoteRecordMutation
	hooks    []Hook
}

// SetUserID sets the "UserID" field.
func (vrc *VoteRecordCreate) SetUserID(s string) *VoteRecordCreate {
	vrc.mutation.SetUserID(s)
	return vrc
}

// SetPollPlayerID sets the "PollPlayerID" field.
func (vrc *VoteRecordCreate) SetPollPlayerID(u ulid.ULID) *VoteRecordCreate {
	vrc.mutation.SetPollPlayerID(u)
	return vrc
}

// SetAnswers sets the "Answers" field.
func (vrc *VoteRecordCreate) SetAnswers(i []int) *VoteRecordCreate {
	vrc.mutation.SetAnswers(i)
	return vrc
}

// SetPlayerID sets the "player" edge to the PollPlayer entity by ID.
func (vrc *VoteRecordCreate) SetPlayerID(id ulid.ULID) *VoteRecordCreate {
	vrc.mutation.SetPlayerID(id)
	return vrc
}

// SetPlayer sets the "player" edge to the PollPlayer entity.
func (vrc *VoteRecordCreate) SetPlayer(p *PollPlayer) *VoteRecordCreate {
	return vrc.SetPlayerID(p.ID)
}

// Mutation returns the VoteRecordMutation object of the builder.
func (vrc *VoteRecordCreate) Mutation() *VoteRecordMutation {
	return vrc.mutation
}

// Save creates the VoteRecord in the database.
func (vrc *VoteRecordCreate) Save(ctx context.Context) (*VoteRecord, error) {
	var (
		err  error
		node *VoteRecord
	)
	if len(vrc.hooks) == 0 {
		if err = vrc.check(); err != nil {
			return nil, err
		}
		node, err = vrc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VoteRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vrc.check(); err != nil {
				return nil, err
			}
			vrc.mutation = mutation
			if node, err = vrc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(vrc.hooks) - 1; i >= 0; i-- {
			if vrc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vrc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, vrc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*VoteRecord)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from VoteRecordMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (vrc *VoteRecordCreate) SaveX(ctx context.Context) *VoteRecord {
	v, err := vrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vrc *VoteRecordCreate) Exec(ctx context.Context) error {
	_, err := vrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vrc *VoteRecordCreate) ExecX(ctx context.Context) {
	if err := vrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vrc *VoteRecordCreate) check() error {
	if _, ok := vrc.mutation.UserID(); !ok {
		return &ValidationError{Name: "UserID", err: errors.New(`ent: missing required field "VoteRecord.UserID"`)}
	}
	if _, ok := vrc.mutation.PollPlayerID(); !ok {
		return &ValidationError{Name: "PollPlayerID", err: errors.New(`ent: missing required field "VoteRecord.PollPlayerID"`)}
	}
	if _, ok := vrc.mutation.Answers(); !ok {
		return &ValidationError{Name: "Answers", err: errors.New(`ent: missing required field "VoteRecord.Answers"`)}
	}
	if _, ok := vrc.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "player", err: errors.New(`ent: missing required edge "VoteRecord.player"`)}
	}
	return nil
}

func (vrc *VoteRecordCreate) sqlSave(ctx context.Context) (*VoteRecord, error) {
	_node, _spec := vrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (vrc *VoteRecordCreate) createSpec() (*VoteRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &VoteRecord{config: vrc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: voterecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: voterecord.FieldID,
			},
		}
	)
	if value, ok := vrc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voterecord.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := vrc.mutation.Answers(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: voterecord.FieldAnswers,
		})
		_node.Answers = value
	}
	if nodes := vrc.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voterecord.PlayerTable,
			Columns: []string{voterecord.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pollplayer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PollPlayerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VoteRecordCreateBulk is the builder for creating many VoteRecord entities in bulk.
type VoteRecordCreateBulk struct {
	config
	builders []*VoteRecordCreate
}

// Save creates the VoteRecord entities in the database.
func (vrcb *VoteRecordCreateBulk) Save(ctx context.Context) ([]*VoteRecord, error) {
	specs := make([]*sqlgraph.CreateSpec, len(vrcb.builders))
	nodes := make([]*VoteRecord, len(vrcb.builders))
	mutators := make([]Mutator, len(vrcb.builders))
	for i := range vrcb.builders {
		func(i int, root context.Context) {
			builder := vrcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoteRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vrcb *VoteRecordCreateBulk) SaveX(ctx context.Context) []*VoteRecord {
	v, err := vrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vrcb *VoteRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := vrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vrcb *VoteRecordCreateBulk) ExecX(ctx context.Context) {
	if err := vrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
