// Code generated by ent, DO NOT EDIT.

package voterecord

const (
	// Label holds the string label denoting the voterecord type in the database.
	Label = "vote_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the userid field in the database.
	FieldUserID = "user_id"
	// FieldPollPlayerID holds the string denoting the pollplayerid field in the database.
	FieldPollPlayerID = "poll_player_id"
	// FieldAnswers holds the string denoting the answers field in the database.
	FieldAnswers = "answers"
	// EdgePlayer holds the string denoting the player edge name in mutations.
	EdgePlayer = "player"
	// Table holds the table name of the voterecord in the database.
	Table = "vote_records"
	// PlayerTable is the table that holds the player relation/edge.
	PlayerTable = "vote_records"
	// PlayerInverseTable is the table name for the PollPlayer entity.
	// It exists in this package in order to avoid circular dependency with the "pollplayer" package.
	PlayerInverseTable = "poll_players"
	// PlayerColumn is the table column denoting the player relation/edge.
	PlayerColumn = "poll_player_id"
)

// Columns holds all SQL columns for voterecord fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPollPlayerID,
	FieldAnswers,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
