// Code generated by ent, DO NOT EDIT.

package voterecord

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	ulid "github.com/oklog/ulid/v2"
	"github.com/tellmeac/go-template/internal/store/sqlstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// UserID applies equality check predicate on the "UserID" field. It's identical to UserIDEQ.
func UserID(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// PollPlayerID applies equality check predicate on the "PollPlayerID" field. It's identical to PollPlayerIDEQ.
func PollPlayerID(v ulid.ULID) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPollPlayerID), v))
	})
}

// UserIDEQ applies the EQ predicate on the "UserID" field.
func UserIDEQ(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "UserID" field.
func UserIDNEQ(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "UserID" field.
func UserIDIn(vs ...string) predicate.VoteRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "UserID" field.
func UserIDNotIn(vs ...string) predicate.VoteRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// UserIDGT applies the GT predicate on the "UserID" field.
func UserIDGT(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUserID), v))
	})
}

// UserIDGTE applies the GTE predicate on the "UserID" field.
func UserIDGTE(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUserID), v))
	})
}

// UserIDLT applies the LT predicate on the "UserID" field.
func UserIDLT(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUserID), v))
	})
}

// UserIDLTE applies the LTE predicate on the "UserID" field.
func UserIDLTE(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUserID), v))
	})
}

// UserIDContains applies the Contains predicate on the "UserID" field.
func UserIDContains(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldUserID), v))
	})
}

// UserIDHasPrefix applies the HasPrefix predicate on the "UserID" field.
func UserIDHasPrefix(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldUserID), v))
	})
}

// UserIDHasSuffix applies the HasSuffix predicate on the "UserID" field.
func UserIDHasSuffix(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldUserID), v))
	})
}

// UserIDEqualFold applies the EqualFold predicate on the "UserID" field.
func UserIDEqualFold(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldUserID), v))
	})
}

// UserIDContainsFold applies the ContainsFold predicate on the "UserID" field.
func UserIDContainsFold(v string) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldUserID), v))
	})
}

// PollPlayerIDEQ applies the EQ predicate on the "PollPlayerID" field.
func PollPlayerIDEQ(v ulid.ULID) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPollPlayerID), v))
	})
}

// PollPlayerIDNEQ applies the NEQ predicate on the "PollPlayerID" field.
func PollPlayerIDNEQ(v ulid.ULID) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPollPlayerID), v))
	})
}

// PollPlayerIDIn applies the In predicate on the "PollPlayerID" field.
func PollPlayerIDIn(vs ...ulid.ULID) predicate.VoteRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPollPlayerID), v...))
	})
}

// PollPlayerIDNotIn applies the NotIn predicate on the "PollPlayerID" field.
func PollPlayerIDNotIn(vs ...ulid.ULID) predicate.VoteRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VoteRecord(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPollPlayerID), v...))
	})
}

// HasPlayer applies the HasEdge predicate on the "player" edge.
func HasPlayer() predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlayerTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerWith applies the HasEdge predicate on the "player" edge with a given conditions (other predicates).
func HasPlayerWith(preds ...predicate.PollPlayer) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlayerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VoteRecord) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VoteRecord) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VoteRecord) predicate.VoteRecord {
	return predicate.VoteRecord(func(s *sql.Selector) {
		p(s.Not())
	})
}
