// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PollsColumns holds the columns for the "polls" table.
	PollsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "question", Type: field.TypeString},
		{Name: "answers", Type: field.TypeJSON},
	}
	// PollsTable holds the schema information for the "polls" table.
	PollsTable = &schema.Table{
		Name:       "polls",
		Columns:    PollsColumns,
		PrimaryKey: []*schema.Column{PollsColumns[0]},
	}
	// PollPlayersColumns holds the columns for the "poll_players" table.
	PollPlayersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "start_at", Type: field.TypeTime},
		{Name: "close_at", Type: field.TypeTime},
		{Name: "multiple_allowed", Type: field.TypeBool},
		{Name: "counters", Type: field.TypeJSON},
		{Name: "poll_id", Type: field.TypeUUID},
	}
	// PollPlayersTable holds the schema information for the "poll_players" table.
	PollPlayersTable = &schema.Table{
		Name:       "poll_players",
		Columns:    PollPlayersColumns,
		PrimaryKey: []*schema.Column{PollPlayersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "poll_players_polls_players",
				Columns:    []*schema.Column{PollPlayersColumns[5]},
				RefColumns: []*schema.Column{PollsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// VoteRecordsColumns holds the columns for the "vote_records" table.
	VoteRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "answers", Type: field.TypeJSON},
		{Name: "poll_player_id", Type: field.TypeUUID},
	}
	// VoteRecordsTable holds the schema information for the "vote_records" table.
	VoteRecordsTable = &schema.Table{
		Name:       "vote_records",
		Columns:    VoteRecordsColumns,
		PrimaryKey: []*schema.Column{VoteRecordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "vote_records_poll_players_records",
				Columns:    []*schema.Column{VoteRecordsColumns[3]},
				RefColumns: []*schema.Column{PollPlayersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "voterecord_user_id_poll_player_id",
				Unique:  true,
				Columns: []*schema.Column{VoteRecordsColumns[1], VoteRecordsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PollsTable,
		PollPlayersTable,
		VoteRecordsTable,
	}
)

func init() {
	PollPlayersTable.ForeignKeys[0].RefTable = PollsTable
	VoteRecordsTable.ForeignKeys[0].RefTable = PollPlayersTable
}
